#+TITLE: 矩阵
#+TYPST_MATH: t

* 考试内容解析

** （一）矩阵及其运算

*** 1. 矩阵的概念

由 \(m times n\) 个数 \(a_(i j)\)（\(i=1,2,dots,m;j=1,2,dots,n\)）排成的 \(m\) 行 \(n\) 列的矩形数表
\[A=mat(delim: "[",a_(11),a_(12),dots,a_(1n);a_(21),a_(22),dots,a_(2n);dots.v,dots.v,,dots.v;a_(m 1),a_(m 2),dots,a_(m n))\]
称为 \(m times n\) 矩阵，简记为 \(A=[a_(i j)]_(m times n)\)。其中 \(a_(i j)\) 叫做矩阵 \(A\) 的位于第 \(i\) 行第 \(j\) 列元素，元素都是实数的矩阵称为实矩阵；元素是复数的矩阵称为复矩阵，除非特别声明，一般讨论的都是实矩阵。

元素全是0的矩阵称为零矩阵，记为 \(O\)。

行数与列数都等于 \(n\) 的矩阵 \(A\) 称为 \(n\) 阶矩阵或 \(n\) 阶方阵。

两个矩阵的行数相等且列数也相等，则称它们是同型矩阵，如果 \(A=[a_(i j)]_(m times n)\) 与 \(B=[b_(i j)]_(m times n)\) 是同型矩阵，当它们的对应元素相等，即 \(a_(i j)=b_(i j)\)（\(i=1,2,dots,m;j=1,2,dots,n\)）时，则称矩阵 \(A\) 与 \(B\) 相等，记为 \(A=B\)。

*** 2. 矩阵的运算

（1）矩阵的加法

设同型矩阵 \(A=[a_(i j)]_(m times n),B=[b_(i j)]_(m times n)\)，则矩阵
\[C=[a_(i j)+b_(i j)]_(m times n)\]
称为矩阵 \(A\) 与 \(B\) 的和，记为 \(C=A+B\)，矩阵 \(A\) 与 \(B\) 的差定义为
\[A-B=A+(-B)=[a_(i j)-b_(i j)]_(m times n),\]
其中 \(-B=[-b_(i j)]_(m times n)\) 称为 \(B\) 的负矩阵。

（2）数乘矩阵

数 \(lambda\) 与矩阵 \(A=[a_(i j)]_(m times n)\) 的乘积记为 \(lambda A\) 或 \(A lambda\)，规定为
\[lambda A=A lambda=[lambda a_(i j)]_(m times n).\]
矩阵的加法与数乘矩阵合起来称为矩阵的线性运算。矩阵的线性运算满足下述运算规律：

1° 交换律　\(A+B=B+A\)；

2° 结合律　\((A+B)+C=A+(B+C)\)；

3° 分配律　\(lambda(A+B)=lambda A+lambda B\)，
\[(lambda+mu)A=lambda A+mu A;\]

4° 数与矩阵相乘的结合律
\[lambda(mu A)=(lambda mu)A.\]

（3）矩阵的乘法

设 \(A=[a_(i j)]\) 是 \(m times s\) 矩阵，\(B=[b_(i j)]\) 是 \(s times n\) 矩阵，则 \(A\) 与 \(B\) 的乘积 \(A B\) 是一个 \(m times n\) 矩阵，记 \(C=A B=[c_(i j)]\)，它的第 \(i\) 行第 \(j\) 列元素 \(c_(i j)\) 是 \(A\) 的第 \(i\) 行的 \(s\) 个元素与 \(B\) 的第 \(j\) 列的 \(s\) 个对应元素乘积之和，即
\[c_(i j)=a_(i 1)b_(1j)+a_(i 2)b_(2j)+dots+a_(i s)b_(s j)=sum_(k=1)^s a_(i k)b_(k j),\]
\[i=1,2,dots,m;j=1,2,dots,n.\]
因此，矩阵 \(A\) 与 \(B\) 可乘的条件是：\(A\) 的列数必须等于 \(B\) 的行数。积矩阵 \(C=A B\) 的行数与 \(A\) 的行数相同，列数与 \(B\) 的列数相同。

矩阵乘法满足下述运算规律：

① 结合律　\((A B)C=A(B C)\)；

② 分配律　\(A(B+C)=A B+A C\)，
\[(A+B)C=A C+B C;\]

③ 数与乘积的结合律
\[lambda(A B)=(lambda A)B=A(lambda B).\]
矩阵的乘法一般不满足交换律，即 \(A B!=B A\)；也没有消去律，即由 \(A B=A C\) 一般不能推出 \(B=C\)。

方阵的幂是利用矩阵乘法规定的，即
\[A^k=underbrace(A A dots A,k"个").\]
方阵的幂具有运算规律 \(A^k A^l=A^(k+l),(A^k)^l=A^(k l)\)，其中 \(k,l\) 为正整数。

设 \(A\) 是 \(n\) 阶方阵，则方阵 \(A\) 的行列式 \(|A|\) 是 \(n\) 阶行列式，且有如下运算规律：设 \(A,B\) 都是 \(n\) 阶方阵，则 \(|k A|=k^n|A|,|A B|=|A| |B|\)。

（4）矩阵的转置

将矩阵 \(A\) 的行与列按原次序互换，所得到的矩阵称为 \(A\) 的转置矩阵，记为 \(A^upright(T)\)。因此，若 \(A\) 是 \(m times n\) 矩阵，则 \(A^upright(T)\) 为 \(n times m\) 矩阵，并且 \(A^upright(T)\) 的第 \(i\) 行第 \(j\) 列元素等于 \(A\) 的第 \(j\) 行第 \(i\) 列元素。

矩阵的转置是一种运算，满足下述运算规律：

① \((A^upright(T))^upright(T)=A\)；

② \((A+B)^upright(T)=A^upright(T)+B^upright(T)\)；

③ \((lambda A)^upright(T)=lambda A^upright(T)\)；

④ \((A B)^upright(T)=B^upright(T)A^upright(T)\)。

*** 3. 特殊矩阵

单位矩阵　主对角线上元素全是1，其余元素均为0的 \(n\) 阶方阵，叫做 \(n\) 阶单位矩阵，记为 \(E\)（若需强调其阶数时，记为 \(E_n\)）。单位矩阵在矩阵乘法中的作用类似于数1在数的乘法中的作用：
\[E_m A_(m times n)=A_(m times n),A_(m times n)E_n=A_(m times n).\]
对于 \(n\) 阶方阵 \(A\)，规定 \(A^0=E\)。

对角矩阵　除主对角线上的元素外，其余元素均为0的 \(n\) 阶方阵，称为 \(n\) 阶对角矩阵。同阶的对角矩阵的和、差、积仍是对角矩阵。

三角矩阵　主对角线以下的元素均为0的 \(n\) 阶方阵称为 \(n\) 阶上三角矩阵；主对角线以上的元素均为0的 \(n\) 阶方阵称为下三角矩阵。同阶的上（下）三角矩阵的和、差、积仍是上（下）三角矩阵。

对称矩阵　满足 \(A^upright(T)=A\) 的 \(n\) 阶方阵 \(A\)，称为 \(n\) 阶对称矩阵。若 \(A,B\) 是同阶的对称矩阵，则 \(A+B,A-B,lambda A\) 也是对称矩阵，但 \(A B\) 不一定是对称矩阵。

反对称矩阵　满足 \(A^upright(T)=-A\) 的 \(n\) 阶方阵，称为 \(n\) 阶反对称矩阵。若 \(A,B\) 是同阶的反对称矩阵，则 \(A+B,A-B,lambda A\) 也是反对称矩阵，但 \(A B\) 不一定是反对称矩阵。

*** 4. 伴随矩阵

设 \(A=[a_(i j)]\) 是 \(n\) 阶方阵，则由行列式 \(|A|\) 的各元素 \(a_(i j)\) 的代数余子式 \(A_(i j)\) 所构成的 \(n\) 阶矩阵
\[A^*=[A_(i j)]^upright(T)=mat(delim: "[",A_(11),A_(12),dots,A_(1n);A_(21),A_(22),dots,A_(2n);dots.v,dots.v,,dots.v;A_(n 1),A_(n 2),dots,A_(n n))^upright(T) \
 =mat(delim: "[",A_(11),A_(21),dots,A_(n 1);A_(12),A_(22),dots,A_(n 2);dots.v,dots.v,,dots.v;A_(1n),A_(2n),dots,A_(n n)),\]
称为矩阵 \(A\) 的伴随矩阵。

任意 \(n\) 阶方阵 \(A\) 与它的伴随矩阵 \(A^*\) 之间有如下关系
\[A A^*=A^* A=|A|E.\]
这是伴随矩阵的一个重要性质。

*** 5. 可逆矩阵与逆矩阵

\(n\) 阶方阵 \(A\) 称为可逆的，如果存在一个 \(n\) 阶方阵 \(B\)，使得
\[A B=B A=E.\]
而把矩阵 \(B\) 叫做 \(A\) 的逆矩阵，记为 \(A^(-1)\)。

\(n\) 阶方阵 \(A\) 可逆的充分必要条件是其行列式 \(|A|!=0\)。当 \(A\) 可逆时，有
\[A^(-1)=1/|A| A^*.\]
行列式为零的方阵称为奇异矩阵，行列式不为零的方阵称为非奇异矩阵。所以，矩阵可逆的充分必要条件是该矩阵是非奇异矩阵。

可逆矩阵有下列性质：

① 若 \(A\) 可逆，则 \(A\) 的逆矩阵是唯一的；

② 若 \(A\) 可逆，则 \(A^(-1)\) 也可逆，且 \((A^(-1))^(-1)=A\)；

③ 若 \(A\) 可逆，数 \(lambda!=0\)，则 \(lambda A\) 可逆，且 \((lambda A)^(-1)=1/lambda A^(-1)\)；

④ 若 \(A,B\) 为同阶可逆矩阵，则 \(A B\) 可逆，且
\[(A B)^(-1)=B^(-1)A^(-1);\]

⑤ 若 \(A\) 可逆，则 \(A^upright(T)\) 也可逆，且 \((A^upright(T))^(-1)=(A^(-1))^upright(T)\)。

** （二）矩阵的初等变换与初等矩阵

*** 1. 矩阵的初等变换

下述三种对矩阵的行施行的变换称为矩阵的初等行变换：

① 互换矩阵的两行；

② 用一个非零数乘矩阵某一行中的所有元素；

③ 把矩阵某一行所有元素的 \(k\) 倍加到另一行对应的元素上去。

在上述三种变换中把行换成列，就得到矩阵的初等列变换。矩阵的初等行变换与初等列变换统称为矩阵的初等变换。

具有如下特征的矩阵称为行阶梯形矩阵：

① 零行（即元素全为零的行）全部位于非零行的下方；

② 各非零行左起第一个非零元素的列指标由上至下是严格增大的。

一个行阶梯形矩阵称为行最简形矩阵，如果其非零行的第一个非零元素为1，并且这些非零元素所在列的其他元素均为0。

对于任何矩阵 \(A\)，总可以经过有限次初等行变换把它化为行阶梯形矩阵和行最简形矩阵。

*** 2. 初等矩阵

单位矩阵经过一次初等变换所得到的矩阵称为初等矩阵。

初等矩阵必是可逆矩阵，且初等矩阵的逆矩阵仍是初等矩阵。用初等矩阵左（右）乘矩阵 \(A\)，相当于对 \(A\) 施行一次相应的初等行（列）变换。

*** 3. 矩阵的等价

如果矩阵 \(A\) 可经过有限次初等变换化为矩阵 \(B\)，则称矩阵 \(A\) 与 \(B\) 等价。

如果矩阵 \(A\) 与 \(B\) 等价，则矩阵 \(B\) 与 \(A\) 也等价；并且若 \(A\) 与 \(B\) 等价，\(B\) 与 \(C\) 等价，则 \(A\) 与 \(C\) 等价。

任一矩阵 \(A\) 都与一个形如 \(mat(delim: "[",E_r,O;O,O)\) 的矩阵等价，其中 \(E_r\) 是 \(r\) 阶单位矩阵，\(r\) 是矩阵 \(A\) 的秩。

** （三）矩阵的秩

*** 1. 矩阵秩的概念及性质

在 \(m times n\) 矩阵 \(A\) 中，任取 \(k\) 行 \(k\) 列（\(k<=min{m,n}\)），位于这些行列交叉处的 \(k^2\) 个元素按其原来次序组成的一个 \(k\) 阶行列式，称为 \(A\) 的一个 \(k\) 阶子式。矩阵 \(A\) 的不为零的子式的最高阶数称为 \(A\) 的秩，记为 \(r(A)\)。

零矩阵的秩规定为0。

设 \(A\) 是 \(m times n\) 矩阵，则有

① \(0<=r(A)<=min{m,n}\)；

② \(r(A^upright(T))=r(A)\)；

③ \(r(k A)=cases(0, & "当" k=0,r(A), & "当" k!=0,)\) 其中 \(k\) 是常数。

\(r(A)>=r\) 的充分必要条件是 \(A\) 中至少有一个 \(r\) 阶子式不为零；\(r(A)<=r\) 的充分必要条件是 \(A\) 的所有 \(r+1\) 阶子式均为零。

特别地，当 \(A\) 是 \(n\) 阶方阵时，\(A\) 的行列式 \(|A|\) 是 \(A\) 的 \(n\) 阶子式。因此，\(r(A)=n\) 的充分必要条件是 \(|A|!=0\)。这时也称方阵 \(A\) 为满秩矩阵。

初等变换不改变矩阵的秩。当 \(P,Q\) 是可逆矩阵时，有
\[r(P A)=r(A Q)=r(P A Q)=r(A).\]
但一般地 \(r(A B)<=min{r(A),r(B)}\)。

*** 2. 用初等变换求矩阵的秩和逆矩阵

由于行阶梯形矩阵和行最简形矩阵的秩等于其非零行的行数，而初等变换又不改变矩阵的秩，所以对矩阵 \(A\) 施行初等行变换化为行阶梯形或行最简形矩阵 \(B\)，则矩阵 \(A\) 的秩 \(r(A)\) 等于矩阵 \(B\) 中非零行的行数。

对矩阵 \([A quad dots.v quad E]\) 施行初等行变换，把 \(A\) 化为单位矩阵 \(E\)，则 \([A quad dots.v quad E]\) 中的 \(E\) 即化为 \(A\) 的逆矩阵 \(A^(-1)\)。这是因为
\[A^(-1)[A quad dots.v quad E]=[E quad dots.v quad A^(-1)].\]
类似地，也可对 \(mat(delim: "[",A;dots;E)\) 施行初等列变换把 \(A\) 化为单位矩阵，则其下边 \(E\) 就化为 \(A^(-1)\)。这种方法可以求解矩阵方程：\(A X=C,X B=C,A X B=C\)。

** （四）分块矩阵及其运算

将矩阵 \(A\) 用若干条纵线和横线分成一些小矩阵，每一个小矩阵称为 \(A\) 的子块，以子块为元素的矩阵称为分块矩阵。矩阵分块是为了便于运算和揭示某些性质，主要是分块对角矩阵的乘法和求逆，例如，设
\[A=mat(delim: "[",A_1,,,;,A_2,,;,,dots.down,;,,,A_s),\]
则
\[A^k=mat(delim: "[",A_1^k,,,;,A_2^k,,;,,dots.down,;,,,A_s^k),\]
\[|A|=|A_1| |A_2| dots |A_s|.\]
从而若 \(|A_i|!=0\)（\(i=1,2,dots,s\)），则 \(|A|!=0\)，故 \(A\) 可逆，且
\[A^(-1)=mat(delim: "[",A_1^(-1),,,;,A_2^(-1),,;,,dots.down,;,,,A_s^(-1)).\]
对矩阵分块时，有两种分块法要特别重视，即按行分块和按列分块：\(A=[A_1 quad A_2 quad dots quad A_n]\) 或
\[A=mat(delim: "[",B_1;B_2;dots.v;B_m).\]
