#+TITLE: 线性方程组

* 考试内容解析

** （一）线性方程组的基本概念

*** 1. 非齐次线性方程组

方程组
$$
\begin{cases}
a_{11}x_{1} + a_{12}x_{2} + \ldots + a_{1n}x_{n} = b_{1} \\
a_{21}x_{1} + a_{22}x_{2} + \ldots + a_{2n}x_{n} = b_{2} \\
\ldots \\
a_{m1}x_{1} + a_{m2}x_{2} + \ldots + a_{mn}x_{n} = b_{m}
\end{cases}
$$
称为 $m$ 个方程 $n$ 个未知量的非齐次线性方程组。如果记矩阵
$$
A = \begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1n} \\
a_{21} & a_{22} & \ldots & a_{2n} \\
 \vdots & \vdots & & \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn}
\end{pmatrix},
$$
$$
\overline{A} = \begin{pmatrix}
a_{11} & a_{12} & \ldots & a_{1n} & b_{1} \\
a_{21} & a_{22} & \ldots & a_{2n} & b_{2} \\
 \vdots & \vdots & & \vdots & \vdots \\
a_{m1} & a_{m2} & \ldots & a_{mn} & b_{m}
\end{pmatrix},
$$
则 $A$ 称为非齐次线性方程组的系数矩阵，$\overline{A}$ 称为非齐次线性方程组的增广矩阵。

非齐次线性方程组的矩阵表示为
$$
A\mathbf{x} = \mathbf{b},
$$
其中 $\mathbf{x} = \left( x_{1},x_{2},\ldots,x_{n} \right)^{T},\mathbf{b} = \left( b_{1},b_{2},\ldots,b_{m} \right)^{T}$。如果系数矩阵按列分块为 $A = \left( \alpha_{1},\alpha_{2},\ldots,\alpha_{n} \right)$，则非齐次线性方程组的向量形式为
$$
x_{1}\alpha_{1} + x_{2}\alpha_{2} + \ldots + x_{n}\alpha_{n} = \mathbf{b}.
$$
如果 $n$ 维列向量 $\xi = \left( c_{1},c_{2},\ldots,c_{n} \right)^{T}$ 满足非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$，即 $A\xi = \mathbf{b}$，则称 $\xi$ 是非齐次线性方程组的一个解向量。

*** 2. 齐次线性方程组

如果非齐次线性方程组的常数项 $b_{i}(i = 1,2,\ldots,m)$ 均为0，即方程组
$$
\begin{cases}
a_{11}x_{1} + a_{12}x_{2} + \ldots + a_{1n}x_{n} = 0 \\
a_{21}x_{1} + a_{22}x_{2} + \ldots + a_{2n}x_{n} = 0 \\
\ldots \\
a_{m1}x_{1} + a_{m2}x_{2} + \ldots + a_{mn}x_{n} = 0
\end{cases},
$$
称为齐次线性方程组。此齐次线性方程组称为非齐次线性方程组的导出组。

齐次线性方程组的矩阵表示为
$$
A\mathbf{x} = \mathbf{0},
$$
其向量形式为
$$
x_{1}\alpha_{1} + x_{2}\alpha_{2} + \ldots + x_{n}\alpha_{n} = \mathbf{0}.
$$

** （二）克莱姆法则

设 $n$ 个方程 $n$ 个未知量的线性方程组
$$
\begin{cases}
a_{11}x_{1} + a_{12}x_{2} + \ldots + a_{1n}x_{n} = b_{1} \\
a_{21}x_{1} + a_{22}x_{2} + \ldots + a_{2n}x_{n} = b_{2} \\
\ldots \\
a_{n1}x_{1} + a_{n2}x_{2} + \ldots + a_{nn}x_{n} = b_{n}
\end{cases}.
$$
如果系数行列式 $D = \det A \neq 0$，则方程组有唯一解
$$
x_{j} = \frac{D_{j}}{D},\quad j = 1,2,\ldots,n,
$$
其中 $D_{j}$ 是方程组的常数项 $b_{1},b_{2},\ldots,b_{n}$ 去替换系数行列式 $D$ 中第 $j$ 列得到的行列式。

注　当系数行列式 $D = 0$ 时，方程组可能有无穷多解，也可能无解。

** （三）线性方程组有解和无解的判定方法

*** 1. 非齐次线性方程组有解的判定定理

非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$ 有解的充分必要条件是 $r(A) = r\left( \overline{A} \right) = r$。并且，当 $r = n$ 时，方程组有唯一解；当 $r < n$ 时，方程组有无穷多解。

*** 2. 齐次线性方程组解的判定定理

齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 有非零解的充分必要条件 $r(A) = r < n$。

（1）当 $m < n$（$m$ 为方程个数，$n$ 为未知量个数）时，齐次线性方程组必有非零解。

（2）当 $m = n$ 时，齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 有非零解的充分必要条件是系数行列式 $\det A = 0$。

*** 3. 用消元法解线性方程组

用消元法解非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$ 的步骤是：

（1）对方程组的增广矩阵 $\overline{A}$ 施行初等行变换，化为阶梯形矩阵，这个过程称为消元过程。

（2）如果 $r(A) \neq r\left( \overline{A} \right)$，则方程组无解；如果 $r(A) = r\left( \overline{A} \right)$，则求出方程组的解。这个过程称为回代过程。

** （四）齐次线性方程组解的结构和通解的求法

*** 1. 齐次线性方程组解的性质

（1）如果 $\eta_{1},\eta_{2}$ 是齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 的解，则 $\eta_{1} + \eta_{2}$ 也是它的解。

（2）如果 $\eta$ 是齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 的解，则对任意常数 $c$，$c\eta$ 也是它的解。

于是，$A\mathbf{x} = \mathbf{0}$ 的解向量的任意线性组合仍是它的解向量，故它的全体解向量构成一个向量空间，称为齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 的解空间。

*** 2. 齐次线性方程组的基础解系

如果 $\eta_{1},\eta_{2},\ldots,\eta_{r}$ 是齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 的解向量的一个极大无关组，则称 $\eta_{1},\eta_{2},\ldots,\eta_{r}$ 是方程组的一个基础解系（即齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 的解空间的基）。

*** 3. 齐次线性方程组解的结构

如果齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 系数矩阵的秩 $r(A) = r < n$，则方程组有基础解系，并且它含有 $n - r$ 个解向量 $\eta_{1},\eta_{2},\ldots,\eta_{n - r}$，方程组的通解（或全部解）为
$$
\mathbf{x} = c_{1}\eta_{1} + c_{2}\eta_{2} + \ldots + c_{n - r}\eta_{n - r},
$$
其中 $c_{1},c_{2},\ldots,c_{n - r}$ 为任意常数。

*** 4. 齐次线性方程组 $A\mathbf{x} = \mathbf{0}$ 通解的求法

（1）对系数矩阵 $A$ 作初等行变换化为阶梯形矩阵。

（2）确定系数矩阵的秩 $r(A) = r$，确定基本未知量和自由未知量。

（3）求出一个基础解系 $\eta_{1},\eta_{2},\ldots,\eta_{n - r}$。

（4）求出方程组的通解 $\mathbf{x} = c_{1}\eta_{1} + c_{2}\eta_{2} + \ldots + c_{n - r}\eta_{n - r}$（$c_{1},c_{2},\ldots,c_{n - r}$ 为任意常数）。

** （五）非齐次线性方程组解的结构和通解的求法

*** 1. 非齐次线性方程组解的性质

（1）如果 $\gamma$ 是非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$ 的一个解，$\eta$ 是它的导出组的一个解，则 $\gamma + \eta$ 是非齐次线性方程组的解。

（2）如果 $\gamma_{1},\gamma_{2}$ 是非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$ 的两个解，则 $\gamma_{1} - \gamma_{2}$ 是其导出组的解。

*** 2. 非齐次线性方程组解的结构

对非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$，如果 $r(A) = r\left( \overline{A} \right) = r < n$，$\eta_{1},\eta_{2},\ldots,\eta_{n - r}$ 是导出组 $A\mathbf{x} = \mathbf{0}$ 的基础解系，$\xi_{0}$ 是 $A\mathbf{x} = \mathbf{b}$ 的一个特解，则非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$ 的通解（或全部解）是
$$
\mathbf{x} = \xi_{0} + c_{1}\eta_{1} + c_{2}\eta_{2} + \ldots + c_{n - r}\eta_{n - r},
$$
其中 $c_{1},c_{2},\ldots,c_{n - r}$ 为任意常数。

*** 3. 非齐次线性方程组 $A\mathbf{x} = \mathbf{b}$ 通解的求法

（1）对增广矩阵 $\overline{A}$ 作初等行变换化为阶梯形矩阵。

（2）求出导出组 $A\mathbf{x} = \mathbf{0}$ 的一个基础解系 $\eta_{1},\eta_{2},\ldots,\eta_{n - r}$。

（3）求出 $A\mathbf{x} = \mathbf{b}$ 的一个特解 $\xi_{0}$。

（4）求出非齐次线性方程组的通解 $\mathbf{x} = \xi_{0} + c_{1}\eta_{1} + c_{2}\eta_{2} + \ldots + c_{n - r}\eta_{n - r}$（$c_{1},c_{2},\ldots,c_{n - r}$ 为任意常数）。
