#+TITLE: 二次型

* 考试内容解析

** （一）基本概念

*** 1. 二次型及其矩阵

$n$ 个变量 $x_{1},x_{2},\ldots,x_{n}$ 的二次齐次函数
$$
\begin{array}{r}
f\left( x_{1},x_{2},\ldots,x_{n} \right) = a_{11}x_{1}^{2} + 2a_{12}x_{1}x_{2} + 2a_{13}x_{1}x_{3} + \ldots + 2a_{1n}x_{1}x_{n} \\
 + a_{22}x_{2}^{2} + 2a_{23}x_{2}x_{3} + \ldots + 2a_{2n}x_{2}x_{n} \\
 + \ldots + a_{nn}x_{n}^{2}
\end{array}
$$
称为一个 $n$ 元二次型。当系数 $a_{ij}(i,j = 1,2,\ldots,n)$ 为实数时，称为实二次型，简称二次型。线性代数一般只讨论实二次型。

如果记 $a_{ij} = a_{ji}(i,j = 1,2,\ldots,n)$，则二次型的矩阵形式为
$$
f\left( \mathbf{x} \right) = \mathbf{x}^{T}A\mathbf{x},
$$
其中 $\mathbf{x} = \left( x_{1},x_{2},\ldots,x_{n} \right)^{T},A = \left( a_{ij} \right)_{n \times n}$ 为 $n$ 阶实对称矩阵。$A$ 称为二次型的矩阵，$A$ 的秩 $r(A)$ 称为二次型的秩。

*** 2. 二次型的标准形和规范形

若二次型中只含有变量的平方项，即
$$
f\left( \mathbf{x} \right) = d_{1}x_{1}^{2} + d_{2}x_{2}^{2} + \ldots + d_{n}x_{n}^{2},
$$
其中 $d_{i}(i = 1,2,\ldots,n)$ 为实数，则该二次型称为标准形。

若标准形中系数 $d_{i}(1 \leq i \leq n)$ 为−1、0或1，即
$$
f\left( \mathbf{x} \right) = x_{1}^{2} + \ldots + x_{p}^{2} - x_{p + 1}^{2} - \ldots - x_{r}^{2}\quad(r \leq n),
$$
则称该二次型为规范形。

*** 3. 矩阵合同

设 $A,B$ 为 $n$ 阶矩阵，如果存在可逆矩阵 $C$，使得
$$
B = C^{T}AC,
$$
则称 $A$ 与 $B$ 合同，记作 $A \approx B$。这种对 $A$ 的运算叫做 $A$ 的合同变换。

矩阵合同具有反身性；对称性；传递性。

** （二）化二次型为标准形或规范形

（1）经可逆线性变换，原二次型的矩阵与新二次型的矩阵合同。

（2）任意一个实二次型经可逆线性变换可化为标准形。此结论也可叙述为：任一实对称矩阵都与一个对角阵合同。

（3）任意一个实二次型 $f\left( \mathbf{x} \right) = \mathbf{x}^{T}A\mathbf{x}$，可经过正交变换 $\mathbf{x} = Q\mathbf{y}$ 化成标准形 $f\left( \mathbf{x} \right) = \lambda_{1}y_{1}^{2} + \ldots + \lambda_{n}y_{n}^{2}$，其中 $\lambda_{1},\ldots,\lambda_{n}$ 为 $A$ 的特征值。

（4）惯性定理　任一实二次型都可以经可逆线性变换化为规范形，且规范形是唯一的。

在二次型的规范形中，正项项数 $p$，负项项数 $r - p$ 是唯一确定的。$p$ 称为其正惯性指数，$r - p$ 称为负惯性指数，$r$ 为二次型的秩。$p - (r - p) = 2p - r$ 称为符号差。

惯性定理也可叙述为：任一实对称矩阵 $A$ 与对角矩阵
$$
\begin{pmatrix}
1 & & & & & & & & \\
 & \ddots & & & & & & & \\
 & & 1 & & & & & & \\
 & & & - 1 & & & & & \\
 & & & & \ddots & & & & \\
 & & & & & - 1 & & & \\
 & & & & & & 0 & & \\
 & & & & & & & \ddots & \\
 & & & & & & & & 0
\end{pmatrix}
$$
合同，其中主对角线元素中1的个数为正惯性指数 $p$，−1的个数为负惯性指数 $r - p$。

** （三）正定二次型和正定矩阵

*** 1. 正定二次型

对于二次型 $f\left( \mathbf{x} \right) = \mathbf{x}^{T}A\mathbf{x}$，如果对任意的 $\mathbf{x} \neq \mathbf{0}$，都有 $\mathbf{x}^{T}A\mathbf{x} > 0$，则称该二次型为正定二次型。此时 $A$ 称为正定矩阵。

*** 2. 二次型正定的充要条件

设二次型 $f\left( \mathbf{x} \right) = \mathbf{x}^{T}A\mathbf{x}$，则以下结论是等价的：

（1）$f$ 的正惯性指数为 $n$。

（2）$A$ 与 $E$ 合同，即存在可逆矩阵 $C$ 使得 $C^{T}AC = E$。

（3）$A$ 的所有特征值都大于零。

（4）$A$ 的各顺序主子式都大于零。

（5）存在可逆矩阵 $C$ 使得 $A = C^{T}C$。

（6）$A$ 是正定矩阵。
