#+TITLE: 函数　极限　连续

* 考试内容解析

** （一）函数

*** 1. 定义

设 $x$ 与 $y$ 是两个变量，$D$ 是实数集的某个子集，若对于 $D$ 中的每个值 $x$，变量 $y$ 按一定的法则有一个确定的值 $y$ 与之对应，称变量 $y$ 为变量 $x$ 的函数，记作
$$
y = f(x).
$$
集合 $D$ 称为函数的定义域，由函数对应法则或实际问题的要求来确定。相应的函数值的全体称为函数的值域。对应法则和定义域是函数的两个要素。

*** 2. 几种特性

1° 有界性　设函数 $y = f(x)$ 在数集 $X$ 上有定义，若存在正数 $M$，使得对于每一个 $x \in X$，都有
$$
|f(x)| \leq M
$$
成立，称 $f(x)$ 在 $X$ 上有界，否则，即这样的 $M$ 不存在，称 $f(x)$ 在 $X$ 上无界。所以函数在 $X$ 上无界，是对任何 $M > 0$，总存在 $x_{0} \in X$，使 $|f\left( x_{0} \right)| > M$。

2° 单调性　设函数 $y = f(x)$ 在区间 $I$ 上有定义，若对于 $I$ 上任意两点 $x_{1}$ 与 $x_{2}$，且 $x_{1} < x_{2}$ 时，均有
$$
f\left( x_{1} \right) < f\left( x_{2} \right)\quad\left\lbrack \text{或 }f\left( x_{1} \right) > f\left( x_{2} \right) \right\rbrack,
$$
称函数 $f(x)$ 在区间 $I$ 上单调增加（或单调减少）。如果其中的“$<$”（或“$>$”）改为“$\leq$”（或“$\geq$”），称函数 $f(x)$ 在区间 $I$ 上单调不减（或单调不增）。

3° 奇偶性　设函数 $y = f(x)$ 的定义域为 $( - a,a)$（$a > 0$），若对于任一 $x \in ( - a,a)$，都有 $f( - x) = f(x)$，称 $f(x)$ 为偶函数，如常数 $C,x^{2},\cos x$ 等，其图像关于 $y$ 轴对称；若对于任一 $x \in ( - a,a)$，都有 $f( - x) = - f(x)$，称 $f(x)$ 为奇函数，如 $x,x^{3},\sin x$ 等，其图像关于坐标原点对称。

4° 周期性　对函数 $y = f(x)$，若存在常数 $T > 0$，使得对于定义域内的任一个 $x$，$x + T$ 仍在其定义域内，且有
$$
f(x + T) = f(x),
$$
称函数 $f(x)$ 为周期函数，$T$ 称为 $f(x)$ 的周期。

*** 3. 复合函数、反函数、隐函数与分段函数

（1）复合函数　设函数 $y = f(u)$ 的定义域为 $D_{f}$，函数 $u = \varphi(x)$ 的值域为 $Z_{\varphi}$，若集合 $D_{f}$ 与 $Z_{\varphi}$ 的交集非空，称函数 $y = f\left\lbrack \varphi(x) \right\rbrack$ 为函数 $y = f(u)$ 与 $u = \varphi(x)$ 复合而成的复合函数，$u$ 为中间变量。对复合函数，重要的是会把它分解，即知道它是由哪些“简单”函数复合而成的。

（2）反函数　设函数 $y = f(x)$ 的值域为 $Z_{f}$，定义域为 $D_{f}$，则对于每一个 $y \in Z_{f}$，必存在 $x \in D_{f}$ 使 $y = f(x)$。若把 $y$ 作为自变量，$x$ 作为因变量，便得另一个函数 $x = \varphi(y)$，且 $f\left\lbrack \varphi(y) \right\rbrack = y$，称 $x = \varphi(y)$ 为 $y = f(x)$ 的反函数。习惯上把 $y = f(x)$ 的反函数记作 $y = \varphi(x)$。$y = f(x)$ 与其反函数 $y = \varphi(x)$ 的图像是关于直线 $y = x$ 对称的。

（3）隐函数　设方程 $F(x,y) = 0$，若当 $x$ 在某区间内取任一值，总有满足该方程唯一的 $y$ 值存在时，称由方程 $F(x,y) = 0$ 在上述区间内确定了一个隐函数 $y = y(x)$。

（4）分段函数　若一个函数在其定义域的不同部分要用不同的式子表示其对应规则，如
$$
f(x) = \begin{cases}
\varphi(x) & a < x < b \\
\psi(x) & c < x < d
\end{cases},
$$
称为分段函数。

** （二）极限

*** 1. 概念

（1）定义1　设 $y = f(x)$ 在 $x_{0}$ 的一个去心邻域 $\left( x_{0} - \delta_{1},x_{0} \right) \cup \left( x_{0},x_{0} + \delta_{1} \right)$ 内有定义，若对于任意给定的 $\varepsilon > 0$，总存在 $\delta > 0$，使得当上述去心邻域内任意 $x$ 满足 $0 < |x - x_{0}| < \delta$ 时，不等式 $|f(x) - a| < \varepsilon$ 恒成立，则称常数 $a$ 为函数 $f(x)$ 在 $x \rightarrow x_{0}$ 时的极限，记作 $\lim\limits_{x \rightarrow x_{0}}f(x) = a$ 或 $f(x) \rightarrow a$（当 $x \rightarrow x_{0}$）。直观地说，即当 $x$ 无限趋近 $x_{0}$ 时，函数 $f(x)$ 无限趋近常数 $a$。

定义2　设 $f(x)$ 在区域 $|x| > E > 0$ 内有定义，若对于任意给定的 $\varepsilon > 0$，存在 $M > 0$，使得当 $|x| > M \geq E$ 时，不等式
$$
|f(x) - a| < \varepsilon
$$
恒成立，则称 $a$ 为当 $x \rightarrow \infty$ 时函数 $f(x)$ 的极限，记作
$$
\lim\limits_{x \rightarrow \infty}f(x) = a.
$$
直观地说，即当 $|x|$ 无限增大时，函数 $f(x)$ 无限趋近常数 $a$。

（2）左极限与右极限　在定义1中，若把“$0 < |x - x_{0}| < \delta$”改为“$x_{0} - \delta < x < x_{0}$”，即自变量 $x$ 从 $x_{0}$ 的左侧趋近于 $x_{0}$，则称 $a$ 为函数 $f(x)$（当 $x \rightarrow x_{0}$）的左极限，记作
$$
\lim\limits_{x \rightarrow x_{0}^{-}}f(x) = a\quad\text{ 或 }\quad f\left( x_{0} - 0 \right) = a;
$$
相应地定义1中的“$0 < |x - x_{0}| < \delta$”改为“$x_{0} < x < x_{0} + \delta$”，则称 $a$ 为函数 $f(x)$（当 $x \rightarrow x_{0}$）的右极限，记作
$$
\lim\limits_{x \rightarrow x_{0}^{+}}f(x) = a\quad\text{ 或 }\quad f\left( x_{0} + 0 \right) = a.
$$
极限存在的充分必要条件：当 $x \rightarrow x_{0}$ 时函数 $f(x)$ 的极限存在的充分必要条件为其左、右极限存在且相等，即 $f\left( x_{0} - 0 \right) = f\left( x_{0} + 0 \right)$。

在定义2中，把 $|x| > M$ 改为 $x > M$，便得到 $x \rightarrow + \infty$ 时函数 $f(x)$ 的极限的定义，即 $\lim\limits_{x \rightarrow + \infty}f(x) = a$，以及把“$|x| > M$”改为 $x \leftarrow M$，便得到 $\lim\limits_{x \rightarrow - \infty}f(x) = a$ 的定义。

注　把数列 $\left\{ x_{n} \right\}$ 看作整标函数即 $x_{n} = f(n)$（$n = 1,2,\ldots$），则数列极限的概念 $\lim\limits_{n \rightarrow \infty}x_{n} = a$ 便是 $f(x)$ 在 $x \rightarrow + \infty$ 的极限的特殊情况：自变量 $x$ 取正整数时，对任意给定的 $\varepsilon > 0$，总存在正整数 $N$，使当 $n > N$ 时，不等式 $|x_{n} - a| < \varepsilon$ 恒成立，则称 $a$ 为数列 $\left\{ x_{n} \right\}$ 的极限，或称此数列收敛于 $a$。

*** 2. 性质

1° 唯一性　在自变量的同一变化过程中（$x \rightarrow x_{0}$ 或 $x \rightarrow \infty$），若函数的极限存在，则此极限唯一。

2° 有界性　若 $\lim\limits_{x \rightarrow x_{0}}f(x) = a$［或 $\lim\limits_{x \rightarrow \infty}f(x) = a$］，则存在 $x_{0}$ 的某去心邻域（或 $|x| > M > 0$），$f(x)$ 在此邻域内（或 $|x| > M > 0$ 内）为有界。

3° 保序性　若 $\lim\limits_{x \rightarrow x_{0}}f(x) = a,\lim\limits_{x \rightarrow x_{0}}g(x) = b$，（或 $\lim\limits_{x \rightarrow \infty}f(x) = a,\lim\limits_{x \rightarrow \infty}g(x) = b$），若 $a < b$，则存在 $x_{0}$ 的某去心邻域（或 $|x| > M > 0$），在此邻域内（或 $|x| > M > 0$），恒有 $f(x) < g(x)$；若在 $x_{0}$ 的某去心邻域内（或 $|x| > M > 0$），恒有 $f(x) \leq g(x)$，则 $a \leq b$。

*** 3. 极限存在准则

夹逼准则：若在 $x_{0}$ 的某去心邻域（或 $|x| > M > 0$）内，恒有
$$
g(x) \leq f(x) \leq h(x),
$$
且 $\lim\limits_{x \rightarrow x_{0}}g(x) = \lim\limits_{x \rightarrow x_{0}}h(x) = a$（或 $\lim\limits_{x \rightarrow \infty}g(x) = \lim\limits_{x \rightarrow \infty}h(x) = a$），则 $\lim\limits_{x \rightarrow x_{0}}f(x) = a$（或 $\lim\limits_{x \rightarrow \infty}f(x) = a$）。

单调有界准则：单调有界数列必收敛。

*** 4. 两个重要极限

（1）$\lim\limits_{x \rightarrow 0}\frac{\sin x}{x} = 1$。

（2）$\lim\limits_{x \rightarrow \infty}\left( 1 + \frac{1}{x} \right)^{x} = e$ 或 $\lim\limits_{x \rightarrow 0}(1 + x)^{\frac{1}{x}} = e$。

*** 5. 极限的四则运算

设在自变量的同一个变化过程中（$x \rightarrow x_{0}$ 或 $x \rightarrow \infty$），$\lim f(x) = a,\lim g(x) = b$，则有

（1）和差：$\lim\left\lbrack f(x) \pm g(x) \right\rbrack = \lim f(x) \pm \lim g(x) = a \pm b$。

（2）积：$\lim\left\lbrack f(x) \cdot g(x) \right\rbrack = \lim f(x) \cdot \lim g(x) = a \cdot b$，特别地 $\lim cf(x) = c\lim f(x) = ca$（其中 $c$ 为常数），$\lim\left\lbrack f(x) \right\rbrack^{k} = \left\lbrack \lim f(x) \right\rbrack^{k} = a^{k}$（其中 $k$ 为正整数）。

（3）商：若 $\lim g(x) = b \neq 0$，则 $\lim\frac{f(x)}{g(x)} = \frac{\lim f(x)}{\lim g(x)} = \frac{a}{b}$。

*** 6. 无穷小与无穷大

（1）无穷小的概念　若 $\lim\limits_{x \rightarrow x_{0}}\alpha(x) = 0$（或 $x \rightarrow \infty$），称 $\alpha(x)$ 为 $x \rightarrow x_{0}$（$x \rightarrow \infty$）时的无穷小，即极限为0的变量为无穷小。常数0也是无穷小。

（2）无穷小性质　$\lim\limits_{x \rightarrow x_{0}}f(x) = a$（或 $x \rightarrow \infty$）的充分必要条件为 $f(x) = a \pm \alpha(x)$，其中 $\alpha(x)$ 为 $x \rightarrow x_{0}$（$x \rightarrow \infty$）的无穷小。

（3）无穷小的运算

1° 加法：有限多个无穷小的和仍为无穷小；

2° 乘法：有限多个无穷小的积仍为无穷小；

3° 有界变量与无穷小的乘积为无穷小。

（4）无穷小的比较

设 $\alpha(x)$ 与 $\beta(x)$ 都是在同一个自变量变化过程中的无穷小，且 $\lim\frac{\alpha(x)}{\beta(x)}$（也就是在此变化过程中的极限）：

若 $\lim\frac{\alpha(x)}{\beta(x)} = 0$，称 $\alpha(x)$ 是比 $\beta(x)$ 高阶的无穷小，记作 $\alpha(x) = o\left( \beta(x) \right)$；

若 $\lim\frac{\alpha(x)}{\beta(x)} = \infty$，称 $\alpha(x)$ 是比 $\beta(x)$ 低阶的无穷小；

若 $\lim\frac{\alpha(x)}{\beta(x)} = c \neq 0$（其中 $c$ 为常数），称 $\alpha(x)$ 与 $\beta(x)$ 是同阶的无穷小；

特别，若 $\lim\frac{\alpha(x)}{\beta(x)} = 1$，称 $\alpha(x)$ 与 $\beta(x)$ 为等价无穷小，记作 $\alpha(x) \sim \beta(x)$。

在求极限过程中，有时利用等价无穷小代换可以化简计算，所以应掌握几个常见的等价无穷小：当 $x \rightarrow 0$ 时，
$$
\sin x \sim x \sim \tan x,
$$
$$
\ln(1 + x) \sim x,
$$
$$
e^{x} - 1 \sim x,
$$
$$
\sqrt[n]{1 + x} - 1 \sim \frac{1}{n}x,
$$
$$
1 - \cos x \sim \frac{1}{2}x^{2}
$$
等等。

（5）无穷大的概念　若 $\lim\limits_{x \rightarrow x_{0}}f(x) = \infty$（或 $x \rightarrow \infty$），称 $f(x)$ 为 $x \rightarrow x_{0}$（$x \rightarrow \infty$）时的无穷大，即绝对值无限增大的变量为无穷大。

（6）无穷小与无穷大之间的关系

在自变量的同一变化过程中，若 $f(x)$ 为无穷大，则其倒数 $\frac{1}{f(x)}$ 必为无穷小；反之，若 $f(x)$ 为无穷小，且 $f(x) \neq 0$，则其倒数 $\frac{1}{f(x)}$ 必为无穷大。

** （三）连续

*** 1. 函数的连续性

（1）连续性的概念　设函数 $y = f(x)$ 在点 $x_{0}$ 的某邻域内有定义，若当自变量增量 $\Delta x = x - x_{0} \rightarrow 0$ 时，对应的函数值增量 $\Delta y = f\left( x_{0} + \Delta x \right) - f\left( x_{0} \right) \rightarrow 0$，即 $\lim\limits_{\Delta x \rightarrow 0}\Delta y = 0$ 或 $\lim\limits_{x \rightarrow x_{0}}f(x) = f\left( x_{0} \right)$，则称函数 $f(x)$ 在 $x_{0}$ 处连续。若 $\lim\limits_{x \rightarrow x_{0}^{-}}f(x) = f\left( x_{0} \right)$，称函数 $f(x)$ 在 $x_{0}$ 处左连续；若 $\lim\limits_{x \rightarrow x_{0}^{+}}f(x) = f\left( x_{0} \right)$，称函数 $f(x)$ 在 $x_{0}$ 处右连续。

显然，函数 $f(x)$ 在 $x_{0}$ 处连续的充分必要条件是 $f(x)$ 在 $x_{0}$ 处既左连续又右连续。

若函数 $f(x)$ 在区间 $(a,b)$ 内每一点都连续，称 $f(x)$ 在开区间 $(a,b)$ 内连续，也称 $f(x)$ 是 $(a,b)$ 内的连续函数；若 $f(x)$ 在 $(a,b)$ 内连续，又在 $a$ 点处右连续，$b$ 点处左连续，则称 $f(x)$ 在闭区间 $\lbrack a,b\rbrack$ 上连续。

（2）运算

1° 加法　有限个在同一点处连续的函数之和，仍在该点处连续；

2° 乘法　有限个在同一点处连续的函数之积，仍在该点处连续；

3° 除法　若 $f(x)$ 与 $g(x)$ 均在点 $x_{0}$ 处连续，且 $g\left( x_{0} \right) \neq 0$，则 $\frac{f(x)}{g(x)}$ 也在 $x_{0}$ 处连续。

（3）复合函数与初等函数的连续性

设函数 $u = \varphi(x)$ 在点 $x = x_{0}$ 处连续，且 $\varphi(x_{0}) = u_{0}$，函数 $y = f(u)$ 在点 $u = u_{0}$ 处连续，则复合函数 $y = f\left\lbrack \varphi(x) \right\rbrack$ 在点 $x_{0}$ 处连续。

一切初等函数在其定义区间上都是连续的。

*** 2. 函数的间断点

（1）函数间断点的概念　若函数 $f(x)$ 在点 $x_{0}$ 处不连续，称 $x_{0}$ 为 $f(x)$ 的间断点。因此，若函数 $f(x)$ 在 $x_{0}$ 处无定义；或 $f(x)$ 在 $x_{0}$ 处虽有定义，但 $\lim\limits_{x \rightarrow x_{0}}f(x)$ 不存在；或虽然 $f(x)$ 在 $x_{0}$ 处有定义，$\lim\limits_{x \rightarrow x_{0}}f(x)$ 存在，但 $\lim\limits_{x \rightarrow x_{0}}f(x) \neq f\left( x_{0} \right)$，此时 $x_{0}$ 便为函数 $y = f(x)$ 的一个间断点。

（2）函数间断点的类型　设 $x = x_{0}$ 为函数 $f(x)$ 的间断点，若 $\lim\limits_{x \rightarrow x_{0}^{+}}f(x)$ 与 $\lim\limits_{x \rightarrow x_{0}^{-}}f(x)$ 都存在，称 $x_{0}$ 为函数 $f(x)$ 的第一类间断点，其他均称为第二类间断点。

在第一类间断点中，左、右极限相等的称为可去间断点，不相等的称为跳跃间断点；无穷间断点与振荡间断点都是第二类间断点。

*** 3. 闭区间上连续函数的性质

1° 最大值和最小值定理　闭区间上的连续函数一定有最大值与最小值。

2° 有界性定理　闭区间上的连续函数在该闭区间上一定有界。

3° 介值定理　设函数 $f(x)$ 在闭区间 $\lbrack a,b\rbrack$ 上连续，且 $f(a) \neq f(b)$，则对于 $f(a)$ 与 $f(b)$ 之间的任一常数 $C$，必在开区间 $(a,b)$ 内至少存在一点 $\xi$，使得 $f(\xi) = C$。

推论　在闭区间上连续的函数必取得介于最大值 $M$ 与最小值 $m$ 之间的任何值。

4° 零点定理　设函数 $f(x)$ 在闭区间 $\lbrack a,b\rbrack$ 上连续，且 $f(a)$ 与 $f(b)$ 异号，则在开区间 $(a,b)$ 内至少存在函数 $f(x)$ 的一个零点，即至少有一点 $\xi \in (a,b)$ 使 $f(\xi) = 0$。
