#+TITLE: 一元函数微分学

* 考试内容解析

** （一）导数概念

1. 导数定义　设函数 $y = f(x)$ 在点 $x_{0}$ 的某邻域内有定义，若自变量从 $x_{0}$ 变到 $x_{0} + \Delta x$ 时，函数的增量 $\Delta y = f\left( x_{0} + \Delta x \right) - f\left( x_{0} \right)$ 与自变量增量 $\Delta x$ 之比的极限
$$
\lim\limits_{\Delta x \rightarrow 0}\frac{\Delta y}{\Delta x} = \lim\limits_{\Delta x \rightarrow 0}\frac{f\left( x_{0} + \Delta x \right) - f\left( x_{0} \right)}{\Delta x}
$$
存在，则称 $f(x)$ 在 $x = x_{0}$ 处可导，此极限值称为 $f(x)$ 在 $x = x_{0}$ 处的导数，记作 $f'\left( x_{0} \right)$，或 $y'|_{x = x_{0}},\frac{dy}{dx}|_{x = x_{0}}$ 等。

2. 左导数：若 $\lim\limits_{\Delta x \rightarrow 0^{-}}\frac{f\left( x_{0} + \Delta x \right) - f\left( x_{0} \right)}{\Delta x}$ 存在，则称此极限值为 $f(x)$ 在 $x = x_{0}$ 处的左导数，记作 $f'_{-}\left( x_{0} \right)$。

3. 右导数：若 $\lim\limits_{\Delta x \rightarrow 0^{+}}\frac{f\left( x_{0} + \Delta x \right) - f\left( x_{0} \right)}{\Delta x}$ 存在，则称此极限值为 $f(x)$ 在 $x = x_{0}$ 处的右导数，记作 $f'_{+}\left( x_{0} \right)$。

4. 若函数 $f(x)$ 在区间 $(a,b)$ 内任意点 $x$ 处的导数 $f'(x)$ 都存在，则称 $f(x)$ 在 $(a,b)$ 内可导。

5. 若函数 $f(x)$ 在 $(a,b)$ 内可导，且 $f'_{+}(a)$ 及 $f'_{-}(b)$ 都存在，则称 $f(x)$ 在闭区间 $\lbrack a,b\rbrack$ 上可导。

** （二）函数可导的条件

1. $f(x)$ 在 $x = x_{0}$ 处可导的必要（非充分）条件是 $f(x)$ 在 $x = x_{0}$ 处连续。

2. $f(x)$ 在 $x = x_{0}$ 处可导的充分与必要条件是 $f'_{-}\left( x_{0} \right)$ 与 $f'_{+}\left( x_{0} \right)$ 存在且相等。

** （三）导数的几何意义与物理意义

1. 设函数 $f(x)$ 可导，则 $f'\left( x_{0} \right)$ 等于曲线 $y = f(x)$ 在点 $\left( x_{0},f\left( x_{0} \right) \right)$ 处切线的斜率。
曲线 $y = f(x)$ 在点 $\left( x_{0},f\left( x_{0} \right) \right)$ 处的切线与法线方程分别是：
$$
y - f\left( x_{0} \right) = f'\left( x_{0} \right)\left( x - x_{0} \right)
$$
和
$$
y - f\left( x_{0} \right) = - \frac{1}{f'\left( x_{0} \right)}\left( x - x_{0} \right).\quad\left\lbrack f'\left( x_{0} \right) \neq 0 \right\rbrack
$$

2. 设一质点作变速直线运动，若其位移 $s$ 随时间 $t$ 的变化规律为函数 $s = s(t)$，则导数 $s'\left( t_{0} \right)$ 表示该质点在时刻 $t_{0}$ 的瞬时速度。

注　导数的物理意义可作多种解释，如细棒状物质的线密度，电路中的电流强度，转动物体的角速度等。

** （四）导数的计算

*** 1. 基本初等函数的导数公式

（1）$(c)' = 0$（$c$ 为常数）；

（2）$\left( x^{\mu} \right)' = \mu x^{\mu - 1}$（$\mu$ 为实数）；

（3）$\left( a^{x} \right)' = a^{x}\ln a$（$a > 0,a \neq 1$）；

（4）$\left( e^{x} \right)' = e^{x}$；

（5）$\left( \log_{a}x \right)' = \frac{1}{x\ln a}$（$a > 0,a \neq 1$）；

（6）$\left( \ln x \right)' = \frac{1}{x}$；

（7）$\left( \sin x \right)' = \cos x$；

（8）$\left( \cos x \right)' = - \sin x$；

（9）$\left( \tan x \right)' = \sec^{2}x$；

（10）$\left( \cot x \right)' = - \csc^{2}x$；

（11）$\left( \sec x \right)' = \sec x\tan x$；

（12）$\left( \csc x \right)' = - \csc x\cot x$；

（13）$\left( \arcsin x \right)' = \frac{1}{\sqrt{1 - x^{2}}}$；

（14）$\left( \arccos x \right)' = - \frac{1}{\sqrt{1 - x^{2}}}$；

（15）$\left( \arctan x \right)' = \frac{1}{1 + x^{2}}$；

（16）$\left( \operatorname{arccot}x \right)' = - \frac{1}{1 + x^{2}}$。

*** 2. 导数的四则运算法则

设函数 $u(x),v(x)$ 都可导，则

（1）$(u \pm v)' = u' \pm v'$；

（2）$(uv)' = u'v + uv'$，特别 $(cu)' = cu'$（$c$ 为常数）；

（3）$\left( \frac{u}{v} \right)' = \frac{u'v - uv'}{v^{2}}$（$v \neq 0$）。

*** 3. 复合函数求导法

设 $u = \varphi(x)$ 在 $x$ 处可导，$y = f(u)$ 在对应的 $u = \varphi(x)$ 处可导，则复合函数 $y = f\left\lbrack \varphi(x) \right\rbrack$ 在 $x$ 处可导，且
$$
\left\{ f\left\lbrack \varphi(x) \right\rbrack \right\}' = f'(u)\varphi'(x),\quad\text{ 即 }\frac{dy}{dx} = \frac{dy}{du} \cdot \frac{du}{dx}.
$$

*** 4. 反函数的导数

若 $x = \varphi(y)$ 在某区间内单调、可导，且 $\varphi'(y) \neq 0$，则其反函数 $y = f(x)$ 在对应的区间内也可导，且
$$
f'(x) = \frac{1}{\varphi'(y)}.
$$

*** 5. 隐函数的导数

设 $y = y(x)$ 是由方程 $F(x,y) = 0$ 所确定的可导函数，注意到 $x$ 是自变量，$y$ 是 $x$ 的函数，$y$ 的函数是 $x$ 的复合函数，在方程的两边同时对 $x$ 求导，可得到一个含有 $y'$ 的方程，从中解出 $y'$ 即是。

注　$y'$ 也可由多元函数微分法中的隐函数求导公式 $\frac{dy}{dx} = - F\frac{'_{x}}{F}'_{y}$ 得到，这里 $y(x)$ 是由方程 $F(x,y) = 0$ 确定的函数。

*** 6. 高阶导数

（1）函数 $y = f(x)$ 导数的导数，称为函数 $f(x)$ 的二阶导数，即 $y'' = (y')'$，记作 $y'' = f''(x)$，或 $\frac{d^{2}y}{dx^{2}},y^{(2)}$。一般地，函数 $y = f(x)$ 的 $n$ 阶导数为 $y^{(n)} = \left\lbrack y^{(n - 1)} \right\rbrack'$，也可写作 $f^{(n)}(x)$ 或 $\frac{d^{n}y}{dx^{n}}$。

（2）设 $u(x),v(x)$ 具有 $n$ 阶导数，则有
$$
\left\lbrack au(x) + bv(x) \right\rbrack^{(n)} = au^{(n)}(x) + bv^{(n)}(x)\quad\left( a,b\text{为常数} \right)
$$
$$
\begin{array}{r}
\left\lbrack u(x)v(x) \right\rbrack^{(n)} = u^{(n)}(x)v(x) + C_{n}^{1}u^{(n - 1)}(x)v'(x) + \ldots \\
 + C_{n}^{k}u^{(n - k)}(x)v^{(k)}(x) + \ldots + u(x)v^{(n)}(x).
\end{array}
$$

*** 7. 由参数方程所确定的函数的导数

设 $y = y(x)$ 是由参数方程 $\begin{cases} x = \varphi(t) \\ y = \psi(t) \end{cases}$，$(\alpha < t < \beta)$ 确定的函数，

（1）若 $\varphi(t)$ 和 $\psi(t)$ 都可导，且 $\varphi'(t) \neq 0$，则
$$
\frac{dy}{dx} = \psi'\frac{t}{\varphi}'(t).
$$

（2）若 $\varphi(t),\psi(t)$ 二阶可导，且 $\varphi'(t) \neq 0$，则
$$
\frac{d^{2}y}{dx^{2}} = \left\lbrack \psi'\frac{t}{\varphi}'(t) \right\rbrack'_{t} \cdot \frac{1}{\varphi}'(t) = \frac{\psi''(t)\varphi'(t) - \psi'(t)\varphi''(t)}{\varphi'^{3}(t)}.
$$

** （五）微分

1. 微分定义　设函数 $y = f(x)$ 在点 $x$ 的某邻域内有定义，若对应于自变量的增量 $\Delta x$，函数的增量 $\Delta y$ 可以表示为 $\Delta y = A\Delta x + o(\Delta x)$，其中 $A$ 与 $\Delta x$ 无关，则称函数 $y = f(x)$ 在点 $x$ 处可微，并把 $A\Delta x$ 称为 $f(x)$ 在点 $x$ 处的微分，记作 $dy$ 或 $df(x)$，即 $dy = A\Delta x$。

2. 函数 $y = f(x)$ 在点 $x$ 处可微的充分必要条件是 $f(x)$ 在 $x$ 处可导，此时 $A = f'(x)$，即有 $dy = f'(x)dx$。

3. 一阶微分形式的不变性　设 $y = f(u)$ 可微，则微分 $dy = f'(u)du$，其中 $u$ 不论是自变量还是中间变量，以上微分形式保持不变。

** （六）微分中值定理

1. 罗尔（Rolle）定理　若函数 $f(x)$ 在闭区间 $\lbrack a,b\rbrack$ 上连续，在开区间 $(a,b)$ 内可导，并且 $f(a) = f(b)$，则在开区间 $(a,b)$ 内至少存在一点 $\xi$，使得 $f'(\xi) = 0$。

2. 拉格朗日（Lagrange）中值定理　若函数 $f(x)$ 在闭区间 $\lbrack a,b\rbrack$ 上连续，在开区间 $(a,b)$ 内可导，则在开区间 $(a,b)$ 内至少存在一点 $\xi$，使得 $f(b) - f(a) = f'(\xi)(b - a)$。

3. 柯西（Cauchy）中值定理　若函数 $f(x)$ 和 $g(x)$ 在闭区间 $\lbrack a,b\rbrack$ 上连续，在开区间 $(a,b)$ 内可导，且 $g'(x) \neq 0$，则在开区间 $(a,b)$ 内至少存在一点 $\xi$，使得 $\frac{f(b) - f(a)}{g(b) - g(a)} = f'\frac{\xi}{g}'(\xi)$。

4. 泰勒（Taylor）定理

（1）假设函数 $f(x)$ 在含有 $x_{0}$ 的开区间 $(a,b)$ 内具有直到 $n$ 阶的导数，则有
$$
f(x) = f\left( x_{0} \right) + f'\left( x_{0} \right)\left( x - x_{0} \right) + \frac{f''\left( x_{0} \right)}{2!}\left( x - x_{0} \right)^{2} + \ldots + \frac{f^{(n)}\left( x_{0} \right)}{n!}\left( x - x_{0} \right)^{n} + o\left\lbrack \left( x - x_{0} \right)^{n} \right\rbrack.
$$
此公式称为带有佩亚诺（Peano）型余项的泰勒公式。

（2）假设函数 $f(x)$ 在含有 $x_{0}$ 的开区间 $(a,b)$ 内具有直到 $(n + 1)$ 阶的导数，则对于 $x \in (a,b)$，有
$$
f(x) = f\left( x_{0} \right) + f'\left( x_{0} \right)\left( x - x_{0} \right) + \frac{f''\left( x_{0} \right)}{2!}\left( x - x_{0} \right)^{2} + \ldots + \frac{f^{(n)}\left( x_{0} \right)}{n!}\left( x - x_{0} \right)^{n} + R_{n}(x),
$$
其中 $R_{n}(x) = \frac{f^{(n + 1)}(\xi)}{(n + 1)!}\left( x - x_{0} \right)^{n + 1}$，$\xi$ 是 $x_{0}$ 与 $x$ 之间的某个值。此公式称为带有拉格朗日型余项的泰勒公式。

注　当 $x_{0} = 0$ 时，以上两公式称为麦克劳林（Maclaurin）公式，即
$$
f(x) = f(0) + f'(0)x + \frac{f''(0)}{2!}x^{2} + \ldots + \frac{f^{(n)}(0)}{n!}x^{n} + o\left( x^{n} \right)
$$
和
$$
f(x) = f(0) + f'(0)x + \frac{f''(0)}{2!}x^{2} + \ldots + \frac{f^{(n)}(0)}{n!}x^{n} + \frac{f^{(n + 1)}(\theta x)}{(n + 1)!}x^{n + 1}\quad(0 < \theta < 1).
$$

** （七）洛必达（L’Hospital）法则

1. $\left( \frac{0}{0} \right)$ 型　设 $f(x),g(x)$ 在点 $x_{0}$ 的某去心邻域内可导，$g'(x) \neq 0$，若 $\lim\limits_{x \rightarrow x_{0}}f(x) = \lim\limits_{x \rightarrow x_{0}}g(x) = 0$，且 $\lim\limits_{x \rightarrow x_{0}}f'\frac{x}{g}'(x)$ 存在或为 $\infty$，则有
$$
\lim\limits_{x \rightarrow x_{0}}\frac{f(x)}{g(x)} = \lim\limits_{x \rightarrow x_{0}}f'\frac{x}{g}'(x).
$$

2. $\left( \frac{\infty}{\infty} \right)$ 型　设 $f(x),g(x)$ 在点 $x_{0}$ 的某去心邻域内可导，$g'(x) \neq 0$，若 $\lim\limits_{x \rightarrow x_{0}}f(x) = \infty,\lim\limits_{x \rightarrow x_{0}}g(x) = \infty$，且 $\lim\limits_{x \rightarrow x_{0}}f'\frac{x}{g}'(x)$ 存在或为 $\infty$，则有
$$
\lim\limits_{x \rightarrow x_{0}}\frac{f(x)}{g(x)} = \lim\limits_{x \rightarrow x_{0}}f'\frac{x}{g}'(x).
$$

注　以上 $x \rightarrow x_{0}$ 的极限过程改为 $x \rightarrow x_{0}^{+},x \rightarrow x_{0}^{-},x \rightarrow \infty,x \rightarrow + \infty$ 或 $x \rightarrow - \infty$ 时，公式仍然成立。

** （八）利用导数研究函数及平面曲线的性态

1. 设函数 $f(x)$ 在 $\lbrack a,b\rbrack$ 上连续，在 $(a,b)$ 内可导，若对任一 $x \in (a,b)$，有 $f'(x) > 0$（$< 0$），则 $f(x)$ 在 $\lbrack a,b\rbrack$ 上单调增加（减少）。

注　若将上面的不等式 $f'(x) > 0$（$< 0$），改为 $f'(x) \geq 0$（$\leq 0$），且使 $f'(x) = 0$ 的点（驻点）只有有限个，则结论仍成立。

2. 判断极值的第一充分条件：设函数 $f(x)$ 在点 $x_{0}$ 的某邻域 $\left( x_{0} - \delta,x_{0} + \delta \right)$ 内连续，$x_{0}$ 是 $f(x)$ 的驻点或不可导点，在 $\left( x_{0} - \delta,x_{0} \right)$ 及 $\left( x_{0},x_{0} + \delta \right)$ 内 $f(x)$ 均可导。

（1）若在 $\left( x_{0} - \delta,x_{0} \right)$ 内 $f'(x) < 0$（$> 0$），而在 $\left( x_{0},x_{0} + \delta \right)$ 内 $f'(x) > 0$（$< 0$），则 $f(x)$ 在 $x_{0}$ 处取得极小值（极大值）；

（2）若在 $\left( x_{0} - \delta,x_{0} \right)$ 和 $\left( x_{0},x_{0} + \delta \right)$ 内 $f'(x)$ 不改变符号，则 $f(x)$ 在 $x_{0}$ 处不取得极值。

3. 判断极值的第二充分条件：设函数 $f(x)$ 在 $x = x_{0}$ 处，一阶导数 $f'\left( x_{0} \right) = 0$，二阶导数 $f''\left( x_{0} \right)$ 存在且不等于零，则当 $f''\left( x_{0} \right) > 0$ 时，$f(x)$ 在 $x_{0}$ 处取得极小值；$f''\left( x_{0} \right) < 0$ 时，$f(x)$ 在 $x_{0}$ 处取得极大值。

4. 曲线凹凸性的判断：若函数 $f(x)$ 在区间 $I$ 上 $f''(x) > 0$（$< 0$），则曲线 $y = f(x)$ 在 $I$ 上上凹或下凸（下凹或上凸）。在连续曲线上，凹凸部分的分界点称为曲线的拐点。

5. 曲线的渐近线

（1）若 $\lim\limits_{x \rightarrow \infty}f(x) = C$（$C$ 为常数），则 $y = C$ 是曲线 $y = f(x)$ 的一条水平渐近线；

（2）若 $\lim\limits_{x \rightarrow x_{0}}f(x) = \infty$，则 $x = x_{0}$ 是曲线 $y = f(x)$ 的一条铅直渐近线；

（3）若 $\lim\limits_{x \rightarrow \infty}\frac{f(x)}{x} = a$，且 $\lim\limits_{x \rightarrow \infty}\left\lbrack f(x) - ax \right\rbrack = b$，则 $y = ax + b$ 是曲线 $y = f(x)$ 的斜渐近线。

注　上面的极限过程 $x \rightarrow x_{0}$ 换成 $x \rightarrow x_{0}^{+}$ 或 $x \rightarrow x_{0}^{-}$，$x \rightarrow \infty$ 换成 $x \rightarrow + \infty$ 或 $x \rightarrow - \infty$，结论也成立。

** （九）平面曲线的曲率

*** 1. 弧微分

设 $y = f(x)$ 是平面内的光滑曲线，则弧微分 $ds = \sqrt{1 + y'^{2}}dx$。

若曲线方程为 $\begin{cases} x = x(t) \\ y = y(t) \end{cases}$，则弧微分为 $ds = \sqrt{\left\lbrack x'(t) \right\rbrack^{2} + \left\lbrack y'(t) \right\rbrack^{2}}dt$。

*** 2. 曲率

（1）设 $M$ 和 $N$ 是曲线上不同的两点，弧 $\overset{\frown}{MN}$ 的长为 $\Delta s$，当 $M$ 点沿曲线到达 $N$ 点时，$M$ 点处的切线所转过的角为 $\Delta\alpha$，则称极限 $K = \lim\limits_{\Delta s \rightarrow 0}\left| \frac{\Delta\alpha}{\Delta s} \right|$ 为该曲线在点 $M$ 处的曲率。

（2）曲率计算公式

若曲线方程为 $y = f(x)$，则曲率 $K = \frac{\left| {y''} \right|}{\left( 1 + y'^{2} \right)^{\frac{3}{2}}}$。

若曲线由参数方程 $\begin{cases} x = x(t) \\ y = y(t) \end{cases}$ 给出，则曲率 $K = \frac{\left| {x'_{t}y''_{t} - y'_{t}x''_{t}} \right|}{\left( x'_{t}^{2} + y'_{t}^{2} \right)^{\frac{3}{2}}}$。

（3）曲率半径 $R = \frac{1}{K}$（$K \neq 0$）。
