#+TITLE: 向量代数与空间解析几何（数学二不要求）
#+TYPST_MATH: t

* 考试内容解析

** （一）向量代数

*** 1. 概念

定义　既有大小，又有方向的量称为向量，记为 $bold(a),bold(b),bold(c)$。起点为 $A$，终点为 $B$ 的向量记为 $arrow(A B)$。与起点无关的向量称为自由向量。向量的长度又称为向量的模，向量 $bold(a)$ 的模记为 $|bold(a)|$。长度为1的向量称为单位向量。长度为零的向量称为零向量。与 $bold(a)$ 长度相等，方向相反的向量称为 $bold(a)$ 的负向量，记为 $-bold(a)$。

若 $bold(a)$ 与 $bold(b)$ 的长度相等，方向相同，则称 $bold(a)$ 与 $bold(b)$ 相等，记为 $bold(a)=bold(b)$。若将 $bold(a)$ 与 $bold(b)$ 起点重合后，$bold(a)$ 与 $bold(b)$ 落在同一直线上，则称 $bold(a)$ 与 $bold(b)$ 平行或共线，记为 $bold(a) parallel bold(b)$。

*** 2. 向量的线性运算

（1）向量的加法与减法

向量 $bold(a)$ 与 $bold(b)$ 的加法服从平行四边形法则，或三角形法则。即若 $bold(a)=arrow(A B),bold(b)=arrow(B C)$，则
$$
bold(a) + bold(b)=arrow(A C).
$$
$bold(a) + (-bold(b))$ 定义为 $bold(a)$ 与 $bold(b)$ 的差，即 $bold(a) - bold(b)=bold(a) + (-bold(b))$。

向量加法满足交换律、结合律等运算规律。

（2）向量的数乘

设 $lambda$ 为实数，$bold(a)$ 为向量，则将下面的向量称为 $lambda$ 与 $bold(a)$ 的数乘，记为 $lambda bold(a)$：

$lambda bold(a)$ 的模为 $|lambda| dot |bold(a)|$，当 $lambda>0$ 时，方向与 $bold(a)$ 相同；当 $lambda<0$ 时，方向与 $bold(a)$ 相反。

向量的数乘满足结合律及分配律等运算规律。

*** 3. 向量的坐标

（1）定义

① 过点 $A$ 作平面 $pi$ 垂直于数轴 $u$，$pi$ 与 $u$ 的交点 $A'$ 称为 $A$ 在 $u$ 轴上的投影。

② 设 $A,B$ 在 $u$ 轴上的投影分别为 $A',B'$，则将 $arrow(A'B')$ 的值 $A'B'$ 称为 $arrow(A B)$ 在 $u$ 轴上的投影，记为 $op("Prj")_u arrow(A B)$。

③ 向量 $bold(a)$ 与 $bold(b)$ 所夹的不超过 $pi$ 的角，称为 $bold(a),bold(b)$ 的夹角，记为 $hat((bold(a),bold(b)))$。$0<=hat((bold(a),bold(b)))<=pi$。

④ 向量 $bold(a)$ 与 $x,y,z$ 轴的夹角 $alpha,beta,gamma$ 称为 $bold(a)$ 的三个方向角。

（2）投影定理

① 设 $arrow(A B)$ 与 $u$ 轴的夹角为 $phi$，则
$$
op("Prj")_u arrow(A B)=|arrow(A B)|cos phi.
$$

② $op("Prj")_u (bold(a) + bold(b))=op("Prj")_u bold(a) + op("Prj")_u bold(b)$。

（3）向量的坐标

设向量 $bold(a)$ 的起点为 $M_1 (x_1,y_1,z_1)$，终点为 $M_2 (x_2,y_2,z_2)$，则 $bold(a)$ 的坐标表达式为
$$
bold(a)={x_2 - x_1,y_2 - y_1,z_2 - z_1}={a_x,a_y,a_z},
$$
其中 $a_x=op("Prj")_x bold(a),a_y=op("Prj")_y bold(a),a_z=op("Prj")_z bold(a)$。

设 $bold(a)={a_x,a_y,a_z},bold(b)={b_x,b_y,b_z}$，则
$$
bold(a) + bold(b)={a_x + b_x,a_y + b_y,a_z + b_z},
$$
$$
lambda bold(a)={lambda a_x,lambda a_y,lambda a_z},
$$
$$
|bold(a)|=sqrt(a_x^2 + a_y^2 + a_z^2),
$$
$$
cos alpha=a_x/ abs(bold(a)) =a_x/sqrt(a_x^2 + a_y^2 + a_z^2),cos beta=a_y/ abs(bold(a)) ,cos gamma=a_z/ abs(bold(a)) ,
$$
$$
cos^2 alpha + cos^2 beta + cos^2 gamma=1.
$$

*** 4. 向量的数量积、向量积与混合积

（1）数量积（内积）

① 定义　$bold(a) dot bold(b)=|bold(a)| |bold(b)|cos hat((bold(a),bold(b)))$。

② 运算律　$bold(a) dot bold(b)=bold(b) dot bold(a)$，$bold(a) dot (bold(b) + bold(c))=bold(a) dot bold(b) + bold(a) dot bold(c)$，$(lambda bold(a)) dot bold(b)=lambda(bold(a) dot bold(b))=bold(a) dot (lambda bold(b))$。

③ 坐标表达式　设 $bold(a)={a_x,a_y,a_z},bold(b)={b_x,b_y,b_z}$，则 $bold(a) dot bold(b)=a_x b_x + a_y b_y + a_z b_z$。

（2）向量积（外积）

① 定义　设 $bold(a),bold(b)$ 为两个向量，将下面的向量 $bold(c)$ 称为 $bold(a)$ 与 $bold(b)$ 的向量积，记为 $bold(a) times bold(b)$。

$|bold(c)|=|bold(a)| |bold(b)|sin hat((bold(a),bold(b)))$，$bold(c) perp bold(a),bold(c) perp bold(b)$，且 $bold(a),bold(b),bold(c)$ 服从右手系。

② 几何意义　模 $|bold(a) times bold(b)|$ 等于以向量 $bold(a),bold(b)$ 为边的平行四边形的面积。

③ 运算律　$bold(a) times bold(b)=-bold(b) times bold(a)$，$(bold(a) + bold(b)) times bold(c)=bold(a) times bold(c) + bold(b) times bold(c)$，$(lambda bold(a)) times bold(b)=bold(a) times(lambda bold(b))=lambda(bold(a) times bold(b))$。

④ 坐标表达式
$$
bold(a) times bold(b)=mat(delim: "|",bold(i),bold(j),bold(k);a_x,a_y,a_z;b_x,b_y,b_z)={mat(delim: "|",a_y,a_z;b_y,b_z),-mat(delim: "|",a_x,a_z;b_x,b_z),mat(delim: "|",a_x,a_y;b_x,b_y)}.
$$

（3）混合积

① 定义　设 $bold(a),bold(b),bold(c)$ 为三个向量，称 $(bold(a) times bold(b)) dot bold(c)$ 为 $bold(a),bold(b),bold(c)$ 的混合积，记为 $[bold(a),bold(b),bold(c)]$。

② 几何意义　$|[bold(a),bold(b),bold(c)]|$ 等于以 $bold(a),bold(b),bold(c)$ 为棱的平行六面体体积。

③ 性质　$[bold(a),bold(b),bold(c)]=[bold(b),bold(c),bold(a)]=[bold(c),bold(a),bold(b)]$（转换对称性），$[bold(a),bold(b),bold(c)]=-[bold(a),bold(c),bold(b)]$。

④ 坐标表达式
$$
[bold(a),bold(b),bold(c)]=mat(delim: "|",a_x,a_y,a_z;b_x,b_y,b_z;c_x,c_y,c_z).
$$

*** 5. 向量的关系

（1）平行

$bold(a) parallel bold(b)$ 的几个充要条件：

① 存在不同时为零的 $lambda,mu$，使 $lambda bold(a) + mu bold(b)=bold(0)$，

② $a_x/b_x=a_y/b_y=a_z/b_z$，

③ $bold(a) times bold(b)=bold(0)$。

（2）垂直　$bold(a) perp bold(b) arrow.l.r.double bold(a) dot bold(b)=0$。

（3）三个向量的共面

$bold(a),bold(b),bold(c)$ 共面的两个充要条件是：

① 存在不全为零的 $lambda_1,lambda_2,lambda_3$，使 $lambda_1 bold(a) + lambda_2 bold(b) + lambda_3 bold(c)=bold(0)$，

② $[bold(a),bold(b),bold(c)]=0$。

** （二）空间平面与直线

*** 1. 平面方程

（1）点法式方程

过点 $P_0 (x_0,y_0,z_0)$，法向量为 $bold(n)={A,B,C}$ 的平面的点法式方程为 $A(x - x_0) + B(y - y_0) + C(z - z_0)=0$。

（2）一般方程　$A x + B y + C z + D=0$。

（3）截距方程　$x/a + y/b + z/c=1$。

（4）点到平面的距离

空间一点 $P_0 (x_0,y_0,z_0)$ 到平面 $pi:A x + B y + C z + D=0$ 的距离为
$$
d= abs(A x_0 + B y_0 + C z_0 + D) /sqrt(A^2 + B^2 + C^2).
$$

*** 2. 直线方程

（1）参数方程

过点 $P_0 (x_0,y_0,z_0)$，方向向量为 $bold(s)={m,n,p}$ 的直线的参数方程为 $cases(x=x_0 + m t,y=y_0 + n t,z=z_0 + p t.)$

（2）标准方程　$(x - x_0)/m=(y - y_0)/n=(z - z_0)/p$。

（3）一般方程　$cases(A_1 x + B_1 y + C_1 z + D_1=0,A_2 x + B_2 y + C_2 z + D_2=0.)$

（4）点到直线的距离　点 $P$ 到过点 $P_0$，且以 $bold(s)$ 为方向向量的直线的距离为 $d= abs(arrow(P P_0) times bold(s)) / abs(bold(s)) $。

*** 3. 直线、平面间的关系

（1）平面与平面的夹角

设平面 $pi_1,pi_2$ 的法向量分别为 $bold(n)_1,bold(n)_2$，$bold(n)_1$ 与 $bold(n)_2$ 所夹的不超过 $pi/2$ 的角 $theta$ 称为 $pi_1$ 与 $pi_2$ 的夹角，$0<=theta<=pi/2$。

$pi_1 parallel pi_2 arrow.l.r.double bold(n)_1 parallel bold(n)_2$，$pi_1 perp pi_2 arrow.l.r.double bold(n)_1 perp bold(n)_2$。

（2）直线与直线的夹角

设直线 $L_1,L_2$ 的方向向量分别为 $bold(s)_1,bold(s)_2$，$bold(s)_1$ 与 $bold(s)_2$ 所夹的不超过 $pi/2$ 的角 $theta$ 称为 $L_1$ 与 $L_2$ 的夹角，$0<=theta<=pi/2$。

$L_1 parallel L_2 arrow.l.r.double bold(s)_1 parallel bold(s)_2$，$L_1 perp L_2 arrow.l.r.double bold(s)_1 perp bold(s)_2$。

（3）直线与平面的夹角

设直线 $L$ 在平面 $pi$ 上的投影直线为 $tilde(L)$，则 $L$ 与 $tilde(L)$ 的夹角 $theta$ 称为直线 $L$ 与平面 $pi$ 的夹角。

设 $L$ 的方向向量为 $bold(s)$，$pi$ 的法向量为 $bold(n)$，则 $sin theta= abs(bold(s) dot bold(n)) /( abs(bold(s))   abs(bold(n)) )$。

$L parallel pi arrow.l.r.double bold(s) perp bold(n)$，$L perp pi arrow.l.r.double bold(s) parallel bold(n)$。

（4）平面束方程

设 $pi_i:A_i x + B_i y + C_i z + D_i=0,i=1,2$，

过 $L:cases(A_1 x + B_1 y + C_1 z + D_1=0,A_2 x + B_2 y + C_2 z + D_2=0)$ 的平面束方程为
$$
A_1 x + B_1 y + C_1 z + D_1 + lambda(A_2 x + B_2 y + C_2 z + D_2)=0 quad ("不含" pi_2)
$$
或
$$
A_2 x + B_2 y + C_2 z + D_2 + lambda(A_1 x + B_1 y + C_1 z + D_1)=0 quad ("不含" pi_1).
$$

** （三）空间曲面与曲线

*** 1. 空间曲面的方程

（1）一般方程　$F(x,y,z)=0$。

（2）参数方程　$cases(x=x(u,v),y=y(u,v),z=z(u,v).)$

*** 2. 空间曲线的方程

（1）参数方程　$cases(x=x(t),y=y(t),z=z(t).)$

（2）一般方程　$cases(F_1 (x,y,z)=0,F_2 (x,y,z)=0.)$

*** 3. 常见曲面与曲线

（1）母线平行于 $z$ 轴的柱面　$F(x,y)=0$。

方程中缺哪个变量，方程就代表母线平行于那个轴的柱面。

（2）旋转面

母线为 $C:cases(f(y,z)=0,x=0,)$，绕 $z$ 轴旋转所得曲面方程为
$$
f(plus.minus sqrt(x^2 + y^2),z)=0.
$$

（3）二次曲面

① 椭球面　$x^2/a^2 + y^2/b^2 + z^2/c^2=1$。

② 双曲面

单叶双曲面　$x^2/a^2 + y^2/b^2 - z^2/c^2=1$。

双叶双曲面　$x^2/a^2 + y^2/b^2 - z^2/c^2=-1$。

③ 抛物面

椭圆抛物面　$x^2/a^2 + y^2/b^2=plus.minus z$。

双曲抛物面　$x^2/a^2 - y^2/b^2=plus.minus z$。

（4）螺旋线　$cases(x=R cos omega t,y=R sin omega t,z=v t.)$

*** 4. 空间曲线在坐标面上的投影曲线

$C:cases(F_1 (x,y,z)=0,F_2 (x,y,z)=0)$，消去 $z$，得到关于 $x y$ 平面的投影柱面 $F(x,y)=0$，$C$ 在 $x y$ 平面上的投影曲线 $cases(F(x,y)=0,z=0.)$
