#+TITLE: 多元函数积分学

* 考试内容解析

** （一）二重积分

*** 1. 二重积分的概念

（1）二重积分定义

设 $f(x,y)$ 是有界闭区域 $D$ 上的有界函数，将闭区域 $D$ 任意分成 $n$ 个小闭区域
$$
\Delta\sigma_{1},\Delta\sigma_{2},\ldots,\Delta\sigma_{n},
$$
其中 $\Delta\sigma_{i}$ 表示第 $i$ 个小闭区域，也表示它的面积。在每个 $\Delta\sigma_{i}$ 上任取一点 $\left( \xi_{i},\eta_{i} \right)$，作乘积 $f\left( \xi_{i},\eta_{i} \right)\Delta\sigma_{i}$（$i = 1,2,\ldots,n$），并作和 $\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i} \right)\Delta\sigma_{i}$。如果当各小闭区域的直径中的最大值 $\lambda$ 趋于零时，这和的极限总存在（与 $\Delta\sigma_{i}$ 的分法及 $\left( \xi_{i},\eta_{i} \right)$ 的取法均无关），则称此极限值为函数 $f(x,y)$ 在闭区域 $D$ 上的二重积分，记作 $\iint_{D}f(x,y)d\sigma$，即
$$
\iint_{D}f(x,y)d\sigma = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i} \right)\Delta\sigma_{i}.
$$
其中 $f(x,y)$ 称为被积函数，$f(x,y)d\sigma$ 称为被积表达式，$d\sigma$ 称为面积元素，$x$ 与 $y$ 称为积分变量，$D$ 称为积分区域，$\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i} \right)\Delta\sigma_{i}$ 称为积分和。

（2）二重积分存在定理

若 $f(x,y)$ 在有界闭区域 $D$ 上连续，则二重积分 $\iint_{D}f(x,y)d\sigma$ 一定存在。

（3）二重积分的几何意义

设 $f(x,y) \geq 0$，二重积分 $\iint_{D}f(x,y)d\sigma$ 表示以 $z = f(x,y)$ 为顶，以 $D$ 为底，侧面是以 $D$ 的边界曲线为准线、母线平行于 $z$ 轴的柱面的曲顶柱体的体积。

*** 2. 二重积分性质

1° $\iint_{D}\left\lbrack k_{1}f_{1}(x,y) + k_{2}f_{2}(x,y) \right\rbrack d\sigma = k_{1}\iint_{D}f_{1}(x,y)d\sigma + k_{2}\iint_{D}f_{2}(x,y)d\sigma$（$k_{1},k_{2}$ 为常数）。

2° 若 $D = D_{1} \cup D_{2}$，且 $D_{1}$ 与 $D_{2}$ 无公共点，则 $\iint_{D}f(x,y)d\sigma = \iint_{D_{1}}f(x,y)d\sigma + \iint_{D_{2}}f(x,y)d\sigma$。

3° $\iint_{D}d\sigma = \sigma$，其中 $\sigma$ 为区域 $D$ 的面积，据此可求平面图形的面积。

4° 若 $f(x,y) \leq g(x,y),(x,y) \in D$，则
$$
\iint_{D}f(x,y)d\sigma \leq \iint_{D}g(x,y)d\sigma,
$$
特别地，
$$
|\iint_{D}f(x,y)d\sigma| \leq \iint_{D}|f(x,y)|d\sigma.
$$

5° 设 $M$ 和 $m$ 是 $f(x,y)$ 在闭区域 $D$ 上最大值和最小值，$\sigma$ 是 $D$ 的面积，则有
$$
m\sigma \leq \iint_{D}f(x,y)d\sigma \leq M\sigma.
$$

6° 二重积分的中值定理　设函数 $f(x,y)$ 在闭区域 $D$ 上连续，$\sigma$ 是 $D$ 的面积，则在 $D$ 上至少存在一点 $(\xi,\eta)$，使得
$$
\iint_{D}f(x,y)d\sigma = f(\xi,\eta) \cdot \sigma.
$$

*** 3. 二重积分的计算法

（1）利用直角坐标计算二重积分

设区域 $D$ 可以用不等式
$$
\varphi_{1}(x) \leq y \leq \varphi_{2}(x),a \leq x \leq b
$$
来表示，则
$$
\iint_{D}f(x,y)d\sigma = \int_{a}^{b}dx\int_{\varphi_{1}(x)}^{\varphi_{2}(x)}f(x,y)dy.
$$
若区域 $D$ 可以用不等式
$$
\psi_{1}(y) \leq x \leq \psi_{2}(y),c \leq y \leq d
$$
来表示，则
$$
\iint_{D}f(x,y)d\sigma = \int_{c}^{d}dy\int_{\psi_{1}(y)}^{\psi_{2}(y)}f(x,y)dx.
$$

（2）利用极坐标计算二重积分

设积分区域 $D$ 可用不等式
$$
\varphi_{1}(\theta) \leq r \leq \varphi_{2}(\theta),\alpha \leq \theta \leq \beta
$$
来表示，则
$$
\begin{array}{r}
\iint_{D}f(x,y)d\sigma = \iint_{D}f\left( r\cos\theta,r\sin\theta \right)rdrd\theta \\
 = \int_{\alpha}^{\beta}d\theta\int_{\varphi_{1}(\theta)}^{\varphi_{2}(\theta)}f\left( r\cos\theta,r\sin\theta \right)rdr.
\end{array}
$$

*** 4. 二重积分应用

（1）曲面面积　设曲面 $S$ 由方程 $z = f(x,y)$ 给出，$D$ 为曲面 $S$ 在 $xOy$ 面上的投影区域，函数 $f(x,y)$ 在 $D$ 上具有一阶连续偏导数，则曲面面积
$$
A = \iint_{D}\sqrt{1 + \left( \frac{\partial f}{\partial x} \right)^{2} + \left( \frac{\partial f}{\partial y} \right)^{2}}d\sigma.
$$

（2）平面薄片的重心　设平面薄片占有 $xOy$ 平面上的闭区域 $D$，在点 $(x,y)$ 处面密度为 $\rho(x,y)$，假定 $\rho(x,y)$ 在 $D$ 上连续，则薄片的重心坐标为
$$
\overline{x} = \frac{\iint_{D}x\rho(x,y)d\sigma}{\iint_{D}\rho(x,y)d\sigma},\quad\overline{y} = \frac{\iint_{D}y\rho(x,y)d\sigma}{\iint_{D}\rho(x,y)d\sigma}.
$$
特别地，若 $\rho(x,y) = \text{常数 }$，则平面图形的形心坐标为
$$
\overline{x} = \frac{1}{A}\iint_{D}xd\sigma,\quad\overline{y} = \frac{1}{A}\iint_{D}yd\sigma,
$$
其中 $A$ 为 $D$ 的面积。

（3）平面薄片的转动惯量　设一薄片占有 $xOy$ 面上闭区域 $D$，在点 $(x,y)$ 处的面密度为 $\rho(x,y)$，假定 $\rho(x,y)$ 在 $D$ 上连续，则薄片对于 $x$ 轴的转动惯量 $I_{x}$，对于 $y$ 轴的转动惯量 $I_{y}$ 以及对于原点的转动惯量 $I_{o}$ 分别为
$$
I_{x} = \iint_{D}y^{2}\rho(x,y)d\sigma,\quad I_{y} = \iint_{D}x^{2}\rho(x,y)d\sigma,\quad I_{o} = \iint_{D}\left( x^{2} + y^{2} \right)\rho(x,y)d\sigma.
$$

（4）平面薄片对质点的引力　设有平面薄片占有 $xOy$ 面上闭区域 $D$，在点 $(x,y)$ 处的面密度为 $\rho(x,y)$，假设 $\rho(x,y)$ 在 $D$ 上连续，则薄片对位于 $z$ 轴上点 $M_{0}(0,0,a)$ 处单位质量的质点的引力
$$
F_{x} = G\iint_{D}\frac{x\rho(x,y)}{\left( x^{2} + y^{2} + a^{2} \right)^{\frac{3}{2}}}d\sigma,
$$
$$
F_{y} = G\iint_{D}\frac{y\rho(x,y)}{\left( x^{2} + y^{2} + a^{2} \right)^{\frac{3}{2}}}d\sigma,
$$
$$
F_{z} = - G\iint_{D}\frac{a\rho(x,y)}{\left( x^{2} + y^{2} + a^{2} \right)^{\frac{3}{2}}}d\sigma.
$$

（以下数学二不要求）

** （二）三重积分

*** 1. 三重积分的概念

（1）三重积分定义

设 $f(x,y,z)$ 是空间闭区域 $\Omega$ 上的有界函数，将 $\Omega$ 任意分成 $n$ 个小闭区域
$$
\Delta v_{1},\Delta v_{2},\ldots,\Delta v_{n},
$$
其中 $\Delta v_{i}$ 表示第 $i$ 个小闭区域，也表示它的体积。在每个 $\Delta v_{i}$ 上任取一点 $\left( \xi_{i},\eta_{i},\zeta_{i} \right)$，作乘积 $f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta v_{i}$（$i = 1,2,\ldots,n$），并作和 $\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta v_{i}$。如果当各小闭区域直径中的最大值 $\lambda$ 趋于零时这和的极限总存在［与 $\Delta v_{i}$ 的分法及 $\left( \xi_{i},\eta_{i},\zeta_{i} \right)$ 的取法均无关］，则称此极限值为函数 $f(x,y,z)$ 在闭区域 $\Omega$ 上的三重积分，记作 $\iiint_{\Omega}f(x,y,z)dv$，即
$$
\iiint_{\Omega}f(x,y,z)dv = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta v_{i}.
$$
其中 $f(x,y,z)$ 称为被积函数，$f(x,y,z)dv$ 称为被积表达式，$dv$ 称为体积元素，$x,y$ 与 $z$ 称为积分变量，$\Omega$ 称为积分区域，$\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta v_{i}$ 称为积分和。

（2）三重积分存在定理

若 $f(x,y,z)$ 在 $\Omega$ 上连续，则三重积分 $\iiint_{\Omega}f(x,y,z)dv$ 一定存在。

（3）三重积分物理意义　设一物体占有 $Oxyz$ 上闭区域 $\Omega$，在点 $(x,y,z)$ 处的体密度为 $\rho(x,y,z)$，假定 $\rho(x,y,z)$ 在 $\Omega$ 上连续，则物体质量 $M$ 为
$$
M = \iiint_{\Omega}\rho(x,y,z)dv.
$$

*** 2. 三重积分性质

二重积分的性质可推广到三重积分，例如中值定理：

假设 $u = f(x,y,z)$ 在空间闭区域 $\Omega$ 上连续，$V$ 是 $\Omega$ 的体积，则至少存在一点 $(\xi,\eta,\zeta) \in \Omega$，使得
$$
\iiint_{\Omega}f(x,y,z)dv = f(\xi,\eta,\zeta) \cdot V.
$$

*** 3. 三重积分的计算法

（1）利用直角坐标计算三重积分

若空间闭区域 $\Omega$ 表示为 $\left\{ (x,y,z)|z_{1}(x,y) \leq z \leq z_{2}(x,y),(x,y) \in D \right\}$，其中
$$
D = \left\{ (x,y)|y_{1}(x) \leq y \leq y_{2}(x),a \leq x \leq b \right\},
$$
则
$$
\begin{array}{r}
\iiint_{\Omega}f(x,y,z)dv = \iint_{D}dxdy\int_{z_{1}(x,y)}^{z_{2}(x,y)}f(x,y,z)dz \\
 = \int_{a}^{b}dx\int_{y_{1}(x)}^{y_{2}(x)}dy\int_{z_{1}(x,y)}^{z_{2}(x,y)}f(x,y,z)dz.
\end{array}
$$
若空间闭区域
$$
\Omega = \left\{ (x,y,z)|(x,y) \in D_{z},c_{1} \leq z \leq c_{2} \right\}
$$
其中 $D_{z}$ 是平行于 $xOy$ 平面、纵坐标为 $z$ 的平面截闭区域 $\Omega$ 所得到的一个平面闭区域，则
$$
\iiint_{\Omega}f(x,y,z)dv = \int_{c_{1}}^{c_{2}}dz\iint_{D_{z}}f(x,y,z)dxdy.
$$

（2）利用柱面坐标计算三重积分

若空间区域 $\Omega$ 可以用不等式
$$
z_{1}(r,\theta) \leq z \leq z_{2}(r,\theta),r_{1}(\theta) \leq r \leq r_{2}(\theta),\alpha \leq \theta \leq \beta
$$
来表示，则
$$
\begin{array}{r}
\iiint_{\Omega}f(x,y,z)dxdydz = \iiint_{\Omega}f\left( r\cos\theta,r\sin\theta,z \right)rdrd\theta dz \\
 = \int_{\alpha}^{\beta}d\theta\int_{r_{1}(\theta)}^{r_{2}(\theta)}rdr\int_{z_{1}(r,\theta)}^{z_{2}(r,\theta)}f\left( r\cos\theta,r\sin\theta,z \right)dz.
\end{array}
$$

（3）利用球面坐标计算三重积分

若空间闭区域 $\Omega$ 表示为 $\left\{ (\rho,\varphi,\theta)|\rho_{1}(\varphi,\theta) \leq \rho \leq \rho_{2}(\varphi,\theta),\varphi_{1}(\theta) \leq \varphi \leq \varphi_{2}(\theta),\alpha \leq \theta \leq \beta \right\}$，则
$$
\begin{array}{r}
\iiint_{\Omega}f(x,y,z)dv \\
 = \iiint_{\Omega}f\left( \rho\sin\varphi\cos\theta,\rho\sin\varphi\sin\theta,\rho\cos\varphi \right)\rho^{2}\sin\varphi d\theta d\varphi d\rho \\
 = \int_{\alpha}^{\beta}d\theta\int_{\varphi_{1}(\theta)}^{\varphi_{2}(\theta)}\sin\varphi d\varphi\int_{\rho_{1}(\varphi,\theta)}^{\rho_{2}(\varphi,\theta)}f\left( \rho\sin\varphi\cos\theta,\rho\sin\varphi\sin\theta,\rho\cos\varphi \right)\rho^{2}d\rho.
\end{array}
$$

*** 4. 三重积分的应用

（1）物体的质心坐标　设物体占有空间域 $\Omega$，在点 $(x,y,z)$ 处的密度为 $\rho(x,y,z)$，假定 $\rho(x,y,z)$ 在 $\Omega$ 上连续，则物体的质心坐标
$$
\overline{x} = \frac{1}{M}\iiint_{\Omega}x\rho(x,y,z)dv,\quad\overline{y} = \frac{1}{M}\iiint_{\Omega}y\rho(x,y,z)dv,\quad\overline{z} = \frac{1}{M}\iiint_{\Omega}z\rho(x,y,z)dv,
$$
其中 $M = \iiint_{\Omega}\rho(x,y,z)dv$。特别地 $\rho(x,y,z) = \text{常数 }$，则形心坐标为
$$
\overline{x} = \frac{1}{V}\iiint_{\Omega}xdv,\quad\overline{y} = \frac{1}{V}\iiint_{\Omega}ydv,\quad\overline{z} = \frac{1}{V}\iiint_{\Omega}zdv,
$$
其中 $V$ 为 $\Omega$ 体积。

（2）物体转动惯量　设物体占有空间域 $\Omega$，在点 $(x,y,z)$ 处密度为 $\rho(x,y,z)$，假定 $\rho(x,y,z)$ 在 $\Omega$ 上连续，则物体关于 $x$ 轴，$xOy$ 平面及原点 $O$ 的转动惯量 $I_{x},I_{xy}$ 及 $I_{o}$ 分别是
$$
I_{x} = \iiint_{\Omega}\left( y^{2} + z^{2} \right)\rho(x,y,z)dv,
$$
$$
I_{xy} = \iiint_{\Omega}z^{2}\rho(x,y,z)dv,
$$
$$
I_{o} = \iiint_{\Omega}\left( x^{2} + y^{2} + z^{2} \right)\rho(x,y,z)dv.
$$

（3）物体对质点的引力

设物体占有空间域 $\Omega$，在点 $(x,y,z)$ 处的密度为 $\rho(x,y,z)$，$\Omega$ 外有一质点 $M_{0}\left( x_{0},y_{0},z_{0} \right)$，其质量为 $m_{0}$，假定 $\rho(x,y,z)$ 在 $\Omega$ 上连续，则物体对质点的引力为 $\overrightarrow{F} = \left\{ F_{x},F_{y},F_{z} \right\}$，其中
$$
F_{x} = \iiint_{\Omega}\frac{km_{0}\rho(x,y,z)(x - x_{0})}{\left\lbrack \left( x - x_{0} \right)^{2} + \left( y - y_{0} \right)^{2} + \left( z - z_{0} \right)^{2} \right\rbrack^{\frac{3}{2}}}dv,
$$
$$
F_{y} = \iiint_{\Omega}\frac{km_{0}\rho(x,y,z)(y - y_{0})}{\left\lbrack \left( x - x_{0} \right)^{2} + \left( y - y_{0} \right)^{2} + \left( z - z_{0} \right)^{2} \right\rbrack^{\frac{3}{2}}}dv,
$$
$$
F_{z} = \iiint_{\Omega}\frac{km_{0}\rho(x,y,z)(z - z_{0})}{\left\lbrack \left( x - x_{0} \right)^{2} + \left( y - y_{0} \right)^{2} + \left( z - z_{0} \right)^{2} \right\rbrack^{\frac{3}{2}}}dv.
$$

** （三）对弧长的曲线积分

*** 1. 对弧长的曲线积分的概念与性质

（1）对弧长曲线积分的定义

设 $L$ 为 $xOy$ 面内的一条以 $A,B$ 为端点的光滑（或分段光滑）曲线弧，函数 $f(x,y)$ 在 $L$ 上有界，在 $L$ 上任意插入 $n - 1$ 个点 $M_{1},M_{2},\ldots,M_{n - 1}$ 把 $L$ 分成 $n$ 个小弧段 $\overset{\frown}{M_{i - 1}M_{i}}$（$i = 1,2,\ldots,n,M_{0} = A,M_{n} = B$），长度为 $\Delta s_{i}$，又在 $\overset{\frown}{M_{i - 1}M_{i}}$ 上任取一点 $\left( \xi_{i},\eta_{i} \right)$，作乘积 $f\left( \xi_{i},\eta_{i} \right)\Delta s_{i}$，并作和 $\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i} \right)\Delta s_{i}$，如果当各小弧段长度的最大值 $\lambda \rightarrow 0$ 时，这和的极限总存在［与 $\Delta s_{i}$ 的分法及 $\left( \xi_{i},\eta_{i} \right)$ 的取法均无关］，则称此极限为函数 $f(x,y)$ 在曲线弧 $L$ 上对弧长的曲线积分或第一类曲线积分，记作 $\int_{L}f(x,y)ds$，即
$$
\int_{L}f(x,y)ds = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i} \right)\Delta s_{i},
$$
其中 $f(x,y)$ 称为被积函数，$f(x,y)ds$ 称为被积表达式，$x$ 与 $y$ 称为积分变量，$L$ 称为积分弧段。

此定义可以类似地推广到积分弧段为空间曲线弧 $\Gamma$ 的情形，即函数 $f(x,y,z)$ 在曲线弧 $\Gamma$ 上对弧长的曲线积分
$$
\int_{\Gamma}f(x,y,z)ds = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta s_{i}.
$$

（2）对弧长的曲线积分的性质

对弧长的曲线积分有类似于重积分的性质，例如
$$
\int_{L}\left\lbrack k_{1}f_{1}(x,y) + k_{2}f_{2}(x,y) \right\rbrack ds = k_{1}\int_{L}f_{1}(x,y)ds + k_{2}\int_{L}f_{2}(x,y)ds\quad\left( k_{1},k_{2}\text{为常数} \right);
$$
$$
\int_{L}f(x,y)ds = \int_{L_{1}}f(x,y)ds + \int_{L_{2}}f(x,y)ds\quad\left( L = L_{1} + L_{2} \right).
$$
设 $f(x,y)$ 在 $L$ 上连续，则在 $L$ 上至少存在一点 $(\xi,\eta)$ 使得
$$
\int_{L}f(x,y)ds = f(\xi,\eta) \cdot S,
$$
其中 $S$ 为曲线弧 $L$ 的长度。

*** 2. 对弧长的曲线积分的计算法

设 $f(x,y)$ 在曲线弧 $L$ 上有定义且连续，$L$ 的参数方程为
$$
\begin{cases}
x = \varphi(t) \\
y = \psi(t)
\end{cases},\quad(\alpha \leq t \leq \beta),
$$
其中 $\varphi(t),\psi(t)$ 在 $\lbrack\alpha,\beta\rbrack$ 上具有一阶连续导数，且 $\varphi'^{2}(t) + \psi'^{2}(t) \neq 0$，则
$$
\int_{L}f(x,y)ds = \int_{\alpha}^{\beta}f\left\lbrack \varphi(t),\psi(t) \right\rbrack\sqrt{\varphi'^{2}(t) + \psi'^{2}(t)}dt.
$$
若曲线 $L$ 由方程
$$
y = \psi(x)\quad\left( x_{0} \leq x \leq X \right)
$$
给出，则
$$
\int_{L}f(x,y)ds = \int_{x_{0}}^{X}f\left\lbrack x,\psi(x) \right\rbrack\sqrt{1 + \psi'^{2}(x)}dx.
$$
若曲线 $L$ 由方程
$$
r = r(\theta)\quad(\alpha \leq \theta \leq \beta)
$$
给出，则
$$
\int_{L}f(x,y)ds = \int_{\alpha}^{\beta}f\left\lbrack r(\theta)\cos\theta,r(\theta)\sin\theta \right\rbrack\sqrt{r^{2}(\theta) + r'^{2}(\theta)}d\theta.
$$
若空间曲线弧 $\Gamma$ 由参数方程
$$
x = x(t),\quad y = y(t),\quad z = z(t)\quad(\alpha \leq t \leq \beta)
$$
给出，则
$$
\int_{\Gamma}f(x,y,z)ds = \int_{\alpha}^{\beta}f\left\lbrack x(t),y(t),z(t) \right\rbrack\sqrt{x'^{2}(t) + y'^{2}(t) + z'^{2}(t)}dt.
$$

*** 3. 对弧长曲线积分的应用

（1）质心坐标　设曲线形物体占有 $xOy$ 平面上弧段 $L$，在点 $P(x,y)$ 处的线密度为 $\rho(x,y)$，假定 $\rho(x,y)$ 在 $L$ 上连续，则曲线形物体质心坐标为
$$
\overline{x} = \frac{1}{M}\int_{L}x\rho(x,y)ds,\quad\overline{y} = \frac{1}{M}\int_{L}y\rho(x,y)ds,
$$
其中 $M = \int_{L}\rho(x,y)ds$。若 $\rho(x,y) = \text{常数 }$，则形心坐标为
$$
\overline{x} = \frac{1}{S}\int_{L}xds,\quad\overline{y} = \frac{1}{S}\int_{L}yds,
$$
其中 $S$ 是弧长。

（2）转动惯量　设曲线形物体占有 $xOy$ 平面上弧段 $L$，在点 $P(x,y)$ 处的线密度为 $\rho(x,y)$，假定 $\rho(x,y)$ 在 $L$ 上连续，则曲线形物体关于 $x$ 轴和原点的转动惯量分别为
$$
I_{x} = \int_{L}y^{2}\rho(x,y)ds,\quad I_{o} = \int_{L}\left( x^{2} + y^{2} \right)\rho(x,y)ds.
$$

** （四）对坐标的曲线积分

*** 1. 对坐标的曲线积分的概念与性质

（1）对坐标曲线积分的定义

设 $L$ 为 $xOy$ 面内从点 $A$ 到点 $B$ 的一条有向光滑（或分段光滑）曲线弧，函数 $P(x,y),Q(x,y)$ 在 $L$ 上有界，在 $L$ 上沿 $L$ 的方向任意插入点列 $M_{1}\left( x_{1},y_{1} \right),M_{2}\left( x_{2},y_{2} \right),\ldots,M_{n - 1}\left( x_{n - 1},y_{n - 1} \right)$ 把 $L$ 分成 $n$ 个有向小弧段 $\overset{\frown}{M_{i - 1}M_{i}}$（$i = 1,2,\ldots,n;M_{0} = A,M_{n} = B$）及 $\Delta x_{i} = x_{i} - x_{i - 1},\Delta y_{i} = y_{i} - y_{i - 1}$，点 $\left( \xi_{i},\eta_{i} \right)$ 为 $\overset{\frown}{M_{i - 1}M_{i}}$ 上任意取定的点。如果当各小弧段长度的最大值 $\lambda \rightarrow 0$ 时，$\sum_{i = 1}^{n}P\left( \xi_{i},\eta_{i} \right)\Delta x_{i}$ 极限总存在［与曲线的分法及 $\left( \xi_{i},\eta_{i} \right)$ 的取法均无关］，则称此极限值为函数 $P(x,y)$ 在有向曲线弧 $L$ 上对坐标 $x$ 的曲线积分，记作 $\int_{L}P(x,y)dx$。类似地，如果极限 $\lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}Q\left( \xi_{i},\eta_{i} \right)\Delta y_{i}$ 总存在［与曲线弧的分法及 $\left( \xi_{i},\eta_{i} \right)$ 的取法均无关］，则称此极限为函数 $Q(x,y)$ 在有向曲线弧 $L$ 上对坐标 $y$ 的曲线积分，记作 $\int_{L}Q(x,y)dy$，即
$$
\int_{L}P(x,y)dx = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}P\left( \xi_{i},\eta_{i} \right)\Delta x_{i},
$$
$$
\int_{L}Q(x,y)dy = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}Q\left( \xi_{i},\eta_{i} \right)\Delta y_{i},
$$
其中 $P(x,y),Q(x,y)$ 称为被积函数，$L$ 称为积分弧段。

一般地
$$
\int_{L}P(x,y)dx + Q(x,y)dy = \int_{L}P(x,y)dx + \int_{L}Q(x,y)dy.
$$
上述定义可以类似地推广到积分弧段为空间有向曲线弧 $\Gamma$ 的情形：
$$
\begin{array}{r}
\int_{\Gamma}P(x,y,z)dx + Q(x,y,z)dy + R(x,y,z)dz \\
 = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}\left\lbrack P\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta x_{i} + Q\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta y_{i} + R\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta z_{i} \right\rbrack.
\end{array}
$$

（2）对坐标曲线积分的性质

若 $L = L_{1} + L_{2}$，则
$$
\begin{array}{r}
\int_{L}P(x,y)dx + Q(x,y)dy \\
 = \int_{L_{1}}P(x,y)dx + Q(x,y)dy + \int_{L_{2}}P(x,y)dx + Q(x,y)dy.
\end{array}
$$
设 $L$ 是有向曲线弧，$- L$ 是与 $L$ 方向相反的有向曲线弧，则
$$
\int_{- L}Pdx + Qdy = - \int_{L}Pdx + Qdy.
$$

*** 2. 对坐标曲线积分的计算法

设 $P(x,y),Q(x,y)$ 在有向曲线弧 $L$ 上连续

（1）若 $L$ 的参数方程为
$$
\begin{cases}
x = \varphi(t) \\
y = \psi(t)
\end{cases},
$$
当 $t$ 单调地由 $\alpha$ 变到 $\beta$ 时，点 $M(x,y)$ 从 $L$ 的起点 $A$ 沿 $L$ 运动到 $B$，$\varphi(t),\psi(t)$ 在以 $\alpha,\beta$ 为端点的闭区间上具有一阶连续导数，且 $\varphi'^{2}(t) + \psi'^{2}(t) \neq 0$，则
$$
\int_{L}P(x,y)dx + Q(x,y)dy = \int_{\alpha}^{\beta}\left\{ P\left\lbrack \varphi(t),\psi(t) \right\rbrack\varphi'(t) + Q\left\lbrack \varphi(t),\psi(t) \right\rbrack\psi'(t) \right\} dt.
$$

（2）若 $L$ 的方程为 $y = \psi(x)$，当 $x$ 单调地由 $a$ 变到 $b$ 时，点 $M(x,y)$ 从 $L$ 起点 $A$ 沿 $L$ 运动到 $B$，$\psi(x)$ 在以 $a,b$ 为端点的闭区间上具有一阶连续导数，则
$$
\int_{L}P(x,y)dx + Q(x,y)dy = \int_{a}^{b}\left\{ P\left\lbrack x,\psi(x) \right\rbrack + Q\left\lbrack x,\psi(x) \right\rbrack\psi'(x) \right\} dx.
$$
若空间曲线弧 $\Gamma$ 由参数方程 $x = x(t),y = y(t),z = z(t)$ 给出，则
$$
\begin{array}{r}
\int_{\Gamma}P(x,y,z)dx + Q(x,y,z)dy + R(x,y,z)dz \\
 = \int_{\alpha}^{\beta}\left\{ P\left\lbrack x(t),y(t),z(t) \right\rbrack x'(t) + Q\left\lbrack x(t),y(t),z(t) \right\rbrack y'(t) + R\left\lbrack x(t),y(t),z(t) \right\rbrack z'(t) \right\} dt,
\end{array}
$$
其中 $\alpha$ 对应于 $\Gamma$ 的起点，$\beta$ 对应于 $\Gamma$ 的终点。

*** 3. 两类曲线积分之间的关系

$$
\int_{L}Pdx + Qdy = \int_{L}\left( P\cos\alpha + Q\cos\beta \right)ds.
$$
其中 $\alpha = \alpha(x,y),\beta = \beta(x,y)$ 为有向曲线弧 $L$ 上点 $(x,y)$ 处的正向切线向量的方向角。

*** 4. 格林公式及其应用

（1）格林公式　设闭区域 $D$ 由分段光滑曲线 $L$ 围成，函数 $P(x,y)$ 及 $Q(x,y)$ 在 $D$ 上具有一阶连续偏导数，则有
$$
\iint_{D}\left( \frac{\partial Q}{\partial x} - \frac{\partial P}{\partial y} \right)dxdy = \oint_{L}Pdx + Qdy,
$$
其中 $L$ 是 $D$ 取正向的边界曲线。

若取 $P = - y,Q = x$，则 $L$ 所围成的区域 $D$ 的面积
$$
A = \frac{1}{2}\oint_{L} - ydx + xdy.
$$

（2）平面上曲线积分与路径无关的条件

设 $P(x,y),Q(x,y)$ 在单连通域 $G$ 内具有一阶连续偏导数，则曲线积分 $\int_{L}Pdx + Qdy$ 在 $G$ 内与路径无关（或沿 $G$ 内任意闭曲线的曲线积分为零）的充分必要条件是在 $G$ 内处处有
$$
\frac{\partial P}{\partial y} = \frac{\partial Q}{\partial x}.
$$

（3）二元函数的全微分求积

设 $P(x,y),Q(x,y)$ 在单连通域 $G$ 内具有一阶连续偏导数，则 $P(x,y)dx + Q(x,y)dy$ 在 $G$ 内为某一函数 $u(x,y)$ 的全微分的充分必要条件是等式
$$
\frac{\partial P}{\partial y} = \frac{\partial Q}{\partial x}
$$
在 $G$ 内恒成立。
$$
\begin{array}{r}
u(x,y) = \int_{\left( x_{0},y_{0} \right)}^{(x,y)}P(x,y)dx + Q(x,y)dy + C \\
 = \int_{x_{0}}^{x}P\left( x,y_{0} \right)dx + \int_{y_{0}}^{y}Q(x,y)dy + C.
\end{array}
$$
或
$$
u(x,y) = \int_{y_{0}}^{y}Q\left( x_{0},y \right)dy + \int_{x_{0}}^{x}P(x,y)dx + C.
$$

*** 5. 对坐标曲线积分的应用

设质点在力
$$
\mathbf{F}(x,y) = F_{x}(x,y)\mathbf{i} + F_{y}(x,y)\mathbf{j}
$$
作用下，沿平面曲线 $C$ 由 $A$ 点移动到 $B$ 点，其中 $F_{x}(x,y),F_{y}(x,y)$ 在 $C$ 上连续，则质点在移动过程中 $\mathbf{F}$ 所做的功
$$
W = \int_{C}F_{x}(x,y)dx + F_{y}(x,y)dy.
$$

** （五）对面积的曲面积分

*** 1. 对面积的曲面积分的概念与性质

（1）对面积曲面积分的定义

设曲面 $\Sigma$ 是光滑（或分片光滑）的，函数 $f(x,y,z)$ 在 $\Sigma$ 上有界，把 $\Sigma$ 任意分成 $n$ 小块 $\Delta S_{i}$（$\Delta S_{i}$ 同时也代表第 $i$ 小块曲面的面积），设 $\left( \xi_{i},\eta_{i},\zeta_{i} \right)$ 是 $\Delta S_{i}$ 上任意取定的一点，作乘积 $f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta S_{i}$（$i = 1,2,\ldots,n$），并作和 $\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta S_{i}$。如果当各小块曲面的直径的最大值 $\lambda \rightarrow 0$ 时，该和的极限总存在［与 $\Delta S_{i}$ 的分法及 $\left( \xi_{i},\eta_{i},\zeta_{i} \right)$ 的取法均无关］，则称此极限值为函数 $f(x,y,z)$ 在曲面 $\Sigma$ 上对面积的曲面积分或第一类曲面积分，记作 $\iint_{\Sigma}f(x,y,z)dS$，即
$$
\iint_{\Sigma}f(x,y,z)dS = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}f\left( \xi_{i},\eta_{i},\zeta_{i} \right)\Delta S_{i},
$$
其中 $f(x,y,z)$ 称为被积函数，$\Sigma$ 称为积分曲面。

（2）对面积的曲面积分的性质　类似于对弧长的曲线积分的性质。

*** 2. 对面积的曲面积分的计算法

设积分曲面 $\Sigma$ 由方程 $z = z(x,y)$ 给出，$\Sigma$ 在 $xOy$ 平面上的投影区域为 $D_{xy}$，函数 $z = z(x,y)$ 在 $D_{xy}$ 上具有连续偏导数，被积函数 $f(x,y,z)$ 在 $\Sigma$ 上连续，则
$$
\iint_{\Sigma}f(x,y,z)dS = \iint_{D_{xy}}f\left( x,y,z(x,y) \right)\sqrt{1 + z'_{x}^{2}(x,y) + z'_{y}^{2}(x,y)}dxdy.
$$

*** 3. 对面积的曲面积分的应用

设有一分布着质量的曲面 $\Sigma$，在点 $(x,y,z)$ 处的面密度为 $\rho(x,y,z)$，假定 $\rho(x,y,z)$ 在 $\Sigma$ 上连续，则质心坐标为
$$
\overline{x} = \frac{1}{M}\iint_{\Sigma}x\rho(x,y,z)dS,
$$
$$
\overline{y} = \frac{1}{M}\iint_{\Sigma}y\rho(x,y,z)dS,
$$
$$
\overline{z} = \frac{1}{M}\iint_{\Sigma}z\rho(x,y,z)dS,
$$
其中 $M = \iint_{\Sigma}\rho(x,y,z)dS$。特别地 $\rho(x,y,z) = \text{常数 }$，则形心坐标
$$
\overline{x} = \frac{1}{S}\iint_{\Sigma}xdS,\quad\overline{y} = \frac{1}{S}\iint_{\Sigma}ydS,\quad\overline{z} = \frac{1}{S}\iint_{\Sigma}zdS,
$$
其中 $S$ 为曲面 $\Sigma$ 的面积。

上述曲面关于 $x$ 轴，$xOy$ 平面，原点的转动惯量分别为
$$
I_{x} = \iint_{\Sigma}\left( y^{2} + z^{2} \right)\rho(x,y,z)dS,
$$
$$
I_{xy} = \iint_{\Sigma}z^{2}\rho(x,y,z)dS,
$$
$$
I_{o} = \iint_{\Sigma}\left( x^{2} + y^{2} + z^{2} \right)\rho(x,y,z)dS.
$$

** （六）对坐标的曲面积分

*** 1. 对坐标的曲面积分的概念与性质

（1）对坐标曲面积分的定义

设 $\Sigma$ 为光滑（或分片光滑）的有向曲面，函数 $R(x,y,z)$ 在 $\Sigma$ 上有界，把 $\Sigma$ 任意分成 $n$ 块小曲面 $\Delta S_{i}$（$\Delta S_{i}$ 又表示第 $i$ 小块曲面的面积），$\Delta S_{i}$ 在 $xOy$ 平面上的投影为 $\left( \Delta S_{i} \right)_{xy}$，$\left( \xi_{i},\eta_{i},\zeta_{i} \right)$ 是 $\Delta S_{i}$ 上任意取定的一点，如果当各小块曲面的直径的最大值 $\lambda \rightarrow 0$ 时，
$$
\lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}R\left( \xi_{i},\eta_{i},\zeta_{i} \right)\left( \Delta S_{i} \right)_{xy}
$$
总存在［与曲面的分法及 $\left( \xi_{i},\eta_{i},\zeta_{i} \right)$ 的取法均无关］，则称此极限值为函数 $R(x,y,z)$ 在有向曲面 $\Sigma$ 上对坐标 $x,y$ 的曲面积分，记作 $\iint_{\Sigma}R(x,y,z)dxdy$，即
$$
\iint_{\Sigma}R(x,y,z)dxdy = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}R\left( \xi_{i},\eta_{i},\zeta_{i} \right)\left( \Delta S_{i} \right)_{xy},
$$
其中 $R(x,y,z)$ 称为被积函数，$\Sigma$ 称为积分曲面。

类似地
$$
\iint_{\Sigma}P(x,y,z)dydz = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}P\left( \xi_{i},\eta_{i},\zeta_{i} \right)\left( \Delta S_{i} \right)_{yz},
$$
$$
\iint_{\Sigma}Q(x,y,z)dzdx = \lim\limits_{\lambda \rightarrow 0}\sum_{i = 1}^{n}Q\left( \xi_{i},\eta_{i},\zeta_{i} \right)\left( \Delta S_{i} \right)_{zx}.
$$
一般地
$$
\begin{array}{r}
\iint_{\Sigma}P(x,y,z)dydz + Q(x,y,z)dzdx + R(x,y,z)dxdy \\
 = \iint_{\Sigma}P(x,y,z)dydz + \iint_{\Sigma}Q(x,y,z)dzdx + \iint_{\Sigma}R(x,y,z)dxdy.
\end{array}
$$

（2）对坐标曲面积分的性质

类似于对坐标的曲线积分，例如

若把 $\Sigma$ 分成 $\Sigma_{1}$ 和 $\Sigma_{2}$，则
$$
\begin{array}{r}
\iint_{\Sigma}Pdydz + Qdzdx + Rdxdy \\
 = \iint_{\Sigma_{1}}Pdydz + Qdzdx + Rdxdy + \iint_{\Sigma_{2}}Pdydz + Qdzdx + Rdxdy.
\end{array}
$$
设 $\Sigma$ 是有向曲面，$- \Sigma$ 是和 $\Sigma$ 取相反侧的有向曲面，则
$$
\iint_{- \Sigma}Pdydz + Qdzdx + Rdxdy = - \iint_{\Sigma}Pdydz + Qdzdx + Rdxdy.
$$

*** 2. 对坐标的曲面积分的计算法

设积分曲面 $\Sigma$ 是由方程 $z = z(x,y)$ 给出，$\Sigma$ 在 $xOy$ 平面上投影区域为 $D_{xy}$，$z = z(x,y)$ 在 $D_{xy}$ 上具有一阶连续偏导数，被积函数 $R(x,y,z)$ 在 $\Sigma$ 上连续，则
$$
\iint_{\Sigma}R(x,y,z)dxdy = \pm \iint_{D_{xy}}R\left( x,y,z(x,y) \right)dxdy,
$$
若曲面 $\Sigma$ 是由方程 $z = z(x,y)$ 所给出的曲面正侧，取正号，反之取负号。

类似地，若曲面 $\Sigma$ 由 $x = x(y,z)$ 给出，则
$$
\iint_{\Sigma}P(x,y,z)dydz = \pm \iint_{D_{yz}}P\left( x(y,z),y,z \right)dydz,
$$
若曲面 $\Sigma$ 是由 $x = x(y,z)$ 给出的曲面前侧，取正号，反之取负号。若曲面 $\Sigma$ 是由 $y = y(x,z)$ 给出，则
$$
\iint_{\Sigma}Q(x,y,z)dzdx = \pm \iint_{D_{zx}}Q\left( x,y(x,z),z \right)dzdx,
$$
若积分曲面 $\Sigma$ 是由 $y = y(x,z)$ 所给出曲面右侧，取正号，反之取负号。

*** 3. 两类曲面之间的关系

$$
\iint_{\Sigma}Pdydz + Qdzdx + Rdxdy = \iint_{\Sigma}\left( P\cos\alpha + Q\cos\beta + R\cos\gamma \right)dS,
$$
其中 $\cos\alpha,\cos\beta,\cos\gamma$ 是有向曲面 $\Sigma$ 上点 $(x,y,z)$ 处的法向量的方向余弦。

*** 4. 高斯公式及应用

（1）高斯公式　设空间闭区域 $\Omega$ 是由分片光滑闭曲面 $\Sigma$ 所围成，函数 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 在 $\Omega$ 上具有一阶连续偏导数，则有
$$
\iiint_{\Omega}\left( \frac{\partial P}{\partial x} + \frac{\partial Q}{\partial y} + \frac{\partial R}{\partial z} \right)dv = \oiint_{\Sigma}Pdydz + Qdzdx + Rdxdy,
$$
其中 $\Sigma$ 是 $\Omega$ 的整个边界曲面取外侧。

（2）取 $P = x,Q = y,R = z$，则空间区域 $\Omega$ 的体积为
$$
V = \frac{1}{3}\oiint_{\Sigma}xdydz + ydzdx + zdxdy.
$$

*** 5. 通量与散度

（1）通量　设某向量场由
$$
\mathbf{A}(x,y,z) = P(x,y,z)\mathbf{i} + Q(x,y,z)\mathbf{j} + R(x,y,z)\mathbf{k}
$$
给出，其中 $P,Q,R$ 具有一阶连续偏导数，$\Sigma$ 是场内的一片有向曲面，$\mathbf{n}^{\circ}$ 是 $\Sigma$ 上点 $(x,y,z)$ 处的单位法向量，则 $\iint_{\Sigma}\mathbf{A} \cdot \mathbf{n}^{\circ}dS$ 称为向量场 $\mathbf{A}$ 通过曲面 $\Sigma$ 向着指定侧的通量。

由定义知 $\iint_{\Sigma}\mathbf{A} \cdot \mathbf{n}^{\circ}dS = \iint_{\Sigma}P(x,y,z)dydz + Q(x,y,z)dzdx + R(x,y,z)dxdy$。

（2）散度　设某向量场由
$$
\mathbf{A}(x,y,z) = P(x,y,z)\mathbf{i} + Q(x,y,z)\mathbf{j} + R(x,y,z)\mathbf{k}
$$
给出，则向量场 $\mathbf{A}$ 在场中一点 $(x,y,z)$ 处散度
$$
\operatorname{div}\mathbf{A} = \frac{\partial P}{\partial x} + \frac{\partial Q}{\partial y} + \frac{\partial R}{\partial z}.
$$

（3）高斯公式向量形式
$$
\iiint_{\Omega}\operatorname{div}\mathbf{A}dv = \oiint_{\Sigma}\mathbf{A} \cdot \mathbf{n}^{\circ}dS = \oiint_{\Sigma}\mathbf{A} \cdot d\mathbf{S} = \oiint_{\Sigma}A_{n}dS
$$
其中 $\Sigma$ 是空间闭区域 $\Omega$ 的边界曲面，而
$$
d\mathbf{S} = \mathbf{n}^{\circ} \cdot dS = \mathbf{i}\cos\alpha dS + \mathbf{j}\cos\beta dS + \mathbf{k}\cos\gamma dS,
$$
$$
A_{n} = \mathbf{A} \cdot \mathbf{n}^{\circ} = P\cos\alpha + Q\cos\beta + R\cos\gamma.
$$

*** 6. 斯托克斯公式

设 $\Gamma$ 为分段光滑的空间有向闭曲线，$\Sigma$ 是以 $\Gamma$ 为边界的分片光滑的有界曲面，$\Gamma$ 的正向与 $\Sigma$ 的侧面符合右手规则，函数 $P(x,y,z),Q(x,y,z),R(x,y,z)$ 在包含 $\Sigma$ 在内的空间域内具有一阶连续偏导数，则
$$
\begin{array}{r}
\oint_{\Gamma}P(x,y,z)dx + Q(x,y,z)dy + R(x,y,z)dz \\
 = \iint_{\Sigma}\left| \begin{matrix}
dydz & dzdx & dxdy \\
\frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z} \\
P & Q & R
\end{matrix} \right| \\
 = \iint_{\Sigma}\left( \frac{\partial R}{\partial y} - \frac{\partial Q}{\partial z} \right)dydz + \left( \frac{\partial P}{\partial z} - \frac{\partial R}{\partial x} \right)dzdx + \left( \frac{\partial Q}{\partial x} - \frac{\partial P}{\partial y} \right)dxdy.
\end{array}
$$

*** 7. 环流量与旋度

（1）环流量　向量场
$$
\mathbf{A}(x,y,z) = P(x,y,z)\mathbf{i} + Q(x,y,z)\mathbf{j} + R(x,y,z)\mathbf{k}
$$
沿场内有向闭曲线 $\Gamma$ 的曲线积分
$$
\oint_{\Gamma}\mathbf{A} \cdot d\mathbf{s} = \oint_{\Gamma}Pdx + Qdy + Rdz
$$
称为向量场 $\mathbf{A}$ 沿有向闭曲线 $\Gamma$ 的环流量。

（2）向量场的旋度　设有向量场
$$
\mathbf{A}(x,y,z) = P(x,y,z)\mathbf{i} + Q(x,y,z)\mathbf{j} + R(x,y,z)\mathbf{k}
$$
则向量场 $\mathbf{A}(x,y,z)$ 在场内一点 $(x,y,z)$ 处旋度
$$
\begin{array}{r}
\operatorname{rot}\mathbf{A} = \left| \begin{matrix}
\mathbf{i} & \mathbf{j} & \mathbf{k} \\
\frac{\partial}{\partial x} & \frac{\partial}{\partial y} & \frac{\partial}{\partial z} \\
P & Q & R
\end{matrix} \right| \\
 = \left( \frac{\partial R}{\partial y} - \frac{\partial Q}{\partial z} \right)\mathbf{i} + \left( \frac{\partial P}{\partial z} - \frac{\partial R}{\partial x} \right)\mathbf{j} + \left( \frac{\partial Q}{\partial x} - \frac{\partial P}{\partial y} \right)\mathbf{k}.
\end{array}
$$

（3）斯托克斯公式向量形式
$$
\oint_{\Gamma}\mathbf{A} \cdot \mathbf{t}^{\circ}ds = \oint_{\Gamma}\mathbf{A} \cdot d\mathbf{s} = \iint_{\Sigma}\operatorname{rot}\mathbf{A} \cdot \mathbf{n}^{\circ}dS,
$$
或
$$
\oint_{\Gamma}A_{t}ds = \iint_{\Sigma}\left( \operatorname{rot}\mathbf{A} \right)_{n}dS.
$$
其中 $\mathbf{n}^{\circ}$ 为有向曲面 $\Sigma$ 在点 $(x,y,z)$ 处的单位法向量，$\mathbf{t}^{\circ}$ 为 $\Sigma$ 正向边界曲线 $\Gamma$ 上点 $(x,y,z)$ 处的单位切向量，$\left( \operatorname{rot}\mathbf{A} \right)_{n} = \operatorname{rot}\mathbf{A} \cdot \mathbf{n}^{\circ}$ 为 $\operatorname{rot}\mathbf{A}$ 在 $\Sigma$ 的法向量上投影，$A_{t} = \mathbf{A} \cdot \mathbf{t}^{\circ}$ 为向量 $\mathbf{A}$ 在 $\Gamma$ 切向量上的投影。
