#+TITLE: 多元函数积分学
#+TYPST_MATH: t

* 考试内容解析

** （一）二重积分

*** 1. 二重积分的概念

（1）二重积分定义

设 \(f(x,y)\) 是有界闭区域 \(D\) 上的有界函数，将闭区域 \(D\) 任意分成 \(n\) 个小闭区域
\[Delta sigma_1,Delta sigma_2,dots,Delta sigma_n,\]
其中 \(Delta sigma_i\) 表示第 \(i\) 个小闭区域，也表示它的面积。在每个 \(Delta sigma_i\) 上任取一点 \((xi_i,eta_i)\)，作乘积 \(f(xi_i,eta_i)Delta sigma_i\)（\(i=1,2,dots,n\)），并作和 \(sum_(i=1)^n f(xi_i,eta_i)Delta sigma_i\)。如果当各小闭区域的直径中的最大值 \(lambda\) 趋于零时，这和的极限总存在（与 \(Delta sigma_i\) 的分法及 \((xi_i,eta_i)\) 的取法均无关），则称此极限值为函数 \(f(x,y)\) 在闭区域 \(D\) 上的二重积分，记作 \(integral.double_D f(x,y)dif sigma\)，即
\[integral.double_D f(x,y)dif sigma=lim_(lambda->0)sum_(i=1)^n f(xi_i,eta_i)Delta sigma_i.\]
其中 \(f(x,y)\) 称为被积函数，\(f(x,y)dif sigma\) 称为被积表达式，\(dif sigma\) 称为面积元素，\(x\) 与 \(y\) 称为积分变量，\(D\) 称为积分区域，\(sum_(i=1)^n f(xi_i,eta_i)Delta sigma_i\) 称为积分和。

（2）二重积分存在定理

若 \(f(x,y)\) 在有界闭区域 \(D\) 上连续，则二重积分 \(integral.double_D f(x,y)dif sigma\) 一定存在。

（3）二重积分的几何意义

设 \(f(x,y)>=0\)，二重积分 \(integral.double_D f(x,y)dif sigma\) 表示以 \(z=f(x,y)\) 为顶，以 \(D\) 为底，侧面是以 \(D\) 的边界曲线为准线、母线平行于 \(z\) 轴的柱面的曲顶柱体的体积。

*** 2. 二重积分性质

1° \(integral.double_D[k_1 f_1(x,y)+k_2 f_2(x,y)]dif sigma=k_1 integral.double_D f_1(x,y)dif sigma+k_2 integral.double_D f_2(x,y)dif sigma\)（\(k_1,k_2\) 为常数）。

2° 若 \(D=D_1 union D_2\)，且 \(D_1\) 与 \(D_2\) 无公共点，则 \(integral.double_D f(x,y)dif sigma=integral.double_(D_1)f(x,y)dif sigma+integral.double_(D_2)f(x,y)dif sigma\)。

3° \(integral.double_D dif sigma=sigma\)，其中 \(sigma\) 为区域 \(D\) 的面积，据此可求平面图形的面积。

4° 若 \(f(x,y)<=g(x,y),(x,y) in D\)，则
\[integral.double_D f(x,y)dif sigma<=integral.double_D g(x,y)dif sigma,\]
特别地，
\[|integral.double_D f(x,y)dif sigma|<=integral.double_D |f(x,y)|dif sigma.\]

5° 设 \(M\) 和 \(m\) 是 \(f(x,y)\) 在闭区域 \(D\) 上最大值和最小值，\(sigma\) 是 \(D\) 的面积，则有
\[m sigma<=integral.double_D f(x,y)dif sigma<=M sigma.\]

6° 二重积分的中值定理　设函数 \(f(x,y)\) 在闭区域 \(D\) 上连续，\(sigma\) 是 \(D\) 的面积，则在 \(D\) 上至少存在一点 \((xi,eta)\)，使得
\[integral.double_D f(x,y)dif sigma=f(xi,eta) dot sigma.\]

*** 3. 二重积分的计算法

（1）利用直角坐标计算二重积分

设区域 \(D\) 可以用不等式
\[phi_1(x)<=y<=phi_2(x),a<=x<=b\]
来表示，则
\[integral.double_D f(x,y)dif sigma=integral_a^b dif x integral_(phi_1(x))^(phi_2(x))f(x,y)dif y.\]
若区域 \(D\) 可以用不等式
\[psi_1(y)<=x<=psi_2(y),c<=y<=d\]
来表示，则
\[integral.double_D f(x,y)dif sigma=integral_c^d dif y integral_(psi_1(y))^(psi_2(y))f(x,y)dif x.\]

（2）利用极坐标计算二重积分

设积分区域 \(D\) 可用不等式
\[phi_1(theta)<=r<=phi_2(theta),alpha<=theta<=beta\]
来表示，则
\[integral.double_D f(x,y)dif sigma=integral.double_D f(r cos theta,r sin theta)r dif r dif theta \
 =integral_alpha^beta dif theta integral_(phi_1(theta))^(phi_2(theta))f(r cos theta,r sin theta)r dif r.\]

*** 4. 二重积分应用

（1）曲面面积　设曲面 \(S\) 由方程 \(z=f(x,y)\) 给出，\(D\) 为曲面 \(S\) 在 \(x O y\) 面上的投影区域，函数 \(f(x,y)\) 在 \(D\) 上具有一阶连续偏导数，则曲面面积
\[A=integral.double_D sqrt(1+((partial f)/(partial x))^2+((partial f)/(partial y))^2)dif sigma.\]

（2）平面薄片的重心　设平面薄片占有 \(x O y\) 平面上的闭区域 \(D\)，在点 \((x,y)\) 处面密度为 \(rho(x,y)\)，假定 \(rho(x,y)\) 在 \(D\) 上连续，则薄片的重心坐标为
\[overline(x)=(integral.double_D x rho(x,y)dif sigma)/(integral.double_D rho(x,y)dif sigma),quad overline(y)=(integral.double_D y rho(x,y)dif sigma)/(integral.double_D rho(x,y)dif sigma).\]
特别地，若 \(rho(x,y)="常数"\)，则平面图形的形心坐标为
\[overline(x)=1/A integral.double_D x dif sigma,quad overline(y)=1/A integral.double_D y dif sigma,\]
其中 \(A\) 为 \(D\) 的面积。

（3）平面薄片的转动惯量　设一薄片占有 \(x O y\) 面上闭区域 \(D\)，在点 \((x,y)\) 处的面密度为 \(rho(x,y)\)，假定 \(rho(x,y)\) 在 \(D\) 上连续，则薄片对于 \(x\) 轴的转动惯量 \(I_x\)，对于 \(y\) 轴的转动惯量 \(I_y\) 以及对于原点的转动惯量 \(I_o\) 分别为
\[I_x=integral.double_D y^2 rho(x,y)dif sigma,quad I_y=integral.double_D x^2 rho(x,y)dif sigma,quad I_o=integral.double_D(x^2+y^2)rho(x,y)dif sigma.\]

（4）平面薄片对质点的引力　设有平面薄片占有 \(x O y\) 面上闭区域 \(D\)，在点 \((x,y)\) 处的面密度为 \(rho(x,y)\)，假设 \(rho(x,y)\) 在 \(D\) 上连续，则薄片对位于 \(z\) 轴上点 \(M_0(0,0,a)\) 处单位质量的质点的引力
\[F_x=G integral.double_D (x rho(x,y))/((x^2+y^2+a^2)^(3/2))dif sigma,\]
\[F_y=G integral.double_D (y rho(x,y))/((x^2+y^2+a^2)^(3/2))dif sigma,\]
\[F_z=-G integral.double_D (a rho(x,y))/((x^2+y^2+a^2)^(3/2))dif sigma.\]

（以下数学二不要求）

** （二）三重积分

*** 1. 三重积分的概念

（1）三重积分定义

设 \(f(x,y,z)\) 是空间闭区域 \(Omega\) 上的有界函数，将 \(Omega\) 任意分成 \(n\) 个小闭区域
\[Delta v_1,Delta v_2,dots,Delta v_n,\]
其中 \(Delta v_i\) 表示第 \(i\) 个小闭区域，也表示它的体积。在每个 \(Delta v_i\) 上任取一点 \((xi_i,eta_i,zeta_i)\)，作乘积 \(f(xi_i,eta_i,zeta_i)Delta v_i\)（\(i=1,2,dots,n\)），并作和 \(sum_(i=1)^n f(xi_i,eta_i,zeta_i)Delta v_i\)。如果当各小闭区域直径中的最大值 \(lambda\) 趋于零时这和的极限总存在［与 \(Delta v_i\) 的分法及 \((xi_i,eta_i,zeta_i)\) 的取法均无关］，则称此极限值为函数 \(f(x,y,z)\) 在闭区域 \(Omega\) 上的三重积分，记作 \(integral.triple_Omega f(x,y,z)dif v\)，即
\[integral.triple_Omega f(x,y,z)dif v=lim_(lambda->0)sum_(i=1)^n f(xi_i,eta_i,zeta_i)Delta v_i.\]
其中 \(f(x,y,z)\) 称为被积函数，\(f(x,y,z)dif v\) 称为被积表达式，\(dif v\) 称为体积元素，\(x,y\) 与 \(z\) 称为积分变量，\(Omega\) 称为积分区域，\(sum_(i=1)^n f(xi_i,eta_i,zeta_i)Delta v_i\) 称为积分和。

（2）三重积分存在定理

若 \(f(x,y,z)\) 在 \(Omega\) 上连续，则三重积分 \(integral.triple_Omega f(x,y,z)dif v\) 一定存在。

（3）三重积分物理意义　设一物体占有 \(O x y z\) 上闭区域 \(Omega\)，在点 \((x,y,z)\) 处的体密度为 \(rho(x,y,z)\)，假定 \(rho(x,y,z)\) 在 \(Omega\) 上连续，则物体质量 \(M\) 为
\[M=integral.triple_Omega rho(x,y,z)dif v.\]

*** 2. 三重积分性质

二重积分的性质可推广到三重积分，例如中值定理：

假设 \(u=f(x,y,z)\) 在空间闭区域 \(Omega\) 上连续，\(V\) 是 \(Omega\) 的体积，则至少存在一点 \((xi,eta,zeta) in Omega\)，使得
\[integral.triple_Omega f(x,y,z)dif v=f(xi,eta,zeta) dot V.\]

*** 3. 三重积分的计算法

（1）利用直角坐标计算三重积分

若空间闭区域 \(Omega\) 表示为 \({(x,y,z)|z_1(x,y)<=z<=z_2(x,y),(x,y) in D}\)，其中
\[D={(x,y)|y_1(x)<=y<=y_2(x),a<=x<=b},\]
则
\[integral.triple_Omega f(x,y,z)dif v=integral.double_D dif x dif y integral_(z_1(x,y))^(z_2(x,y))f(x,y,z)dif z \
 =integral_a^b dif x integral_(y_1(x))^(y_2(x))dif y integral_(z_1(x,y))^(z_2(x,y))f(x,y,z)dif z.\]
若空间闭区域
\[Omega={(x,y,z)|(x,y) in D_z,c_1<=z<=c_2}\]
其中 \(D_z\) 是平行于 \(x O y\) 平面、纵坐标为 \(z\) 的平面截闭区域 \(Omega\) 所得到的一个平面闭区域，则
\[integral.triple_Omega f(x,y,z)dif v=integral_(c_1)^(c_2)dif z integral.double_(D_z)f(x,y,z)dif x dif y.\]

（2）利用柱面坐标计算三重积分

若空间区域 \(Omega\) 可以用不等式
\[z_1(r,theta)<=z<=z_2(r,theta),r_1(theta)<=r<=r_2(theta),alpha<=theta<=beta\]
来表示，则
\[integral.triple_Omega f(x,y,z)dif x dif y dif z=integral.triple_Omega f(r cos theta,r sin theta,z)r dif r dif theta dif z \
 =integral_alpha^beta dif theta integral_(r_1(theta))^(r_2(theta))r dif r integral_(z_1(r,theta))^(z_2(r,theta))f(r cos theta,r sin theta,z)dif z.\]

（3）利用球面坐标计算三重积分

若空间闭区域 \(Omega\) 表示为 \({(rho,phi,theta)|rho_1(phi,theta)<=rho<=rho_2(phi,theta),phi_1(theta)<=phi<=phi_2(theta),alpha<=theta<=beta}\)，则
\[integral.triple_Omega f(x,y,z)dif v \
 =integral.triple_Omega f(rho sin phi cos theta,rho sin phi sin theta,rho cos phi)rho^2 sin phi dif theta dif phi dif rho \
 =integral_alpha^beta dif theta integral_(phi_1(theta))^(phi_2(theta))sin phi dif phi integral_(rho_1(phi,theta))^(rho_2(phi,theta))f(rho sin phi cos theta,rho sin phi sin theta,rho cos phi)rho^2 dif rho.\]

*** 4. 三重积分的应用

（1）物体的质心坐标　设物体占有空间域 \(Omega\)，在点 \((x,y,z)\) 处的密度为 \(rho(x,y,z)\)，假定 \(rho(x,y,z)\) 在 \(Omega\) 上连续，则物体的质心坐标
\[overline(x)=1/M integral.triple_Omega x rho(x,y,z)dif v,quad overline(y)=1/M integral.triple_Omega y rho(x,y,z)dif v,quad overline(z)=1/M integral.triple_Omega z rho(x,y,z)dif v,\]
其中 \(M=integral.triple_Omega rho(x,y,z)dif v\)。特别地 \(rho(x,y,z)="常数"\)，则形心坐标为
\[overline(x)=1/V integral.triple_Omega x dif v,quad overline(y)=1/V integral.triple_Omega y dif v,quad overline(z)=1/V integral.triple_Omega z dif v,\]
其中 \(V\) 为 \(Omega\) 体积。

（2）物体转动惯量　设物体占有空间域 \(Omega\)，在点 \((x,y,z)\) 处密度为 \(rho(x,y,z)\)，假定 \(rho(x,y,z)\) 在 \(Omega\) 上连续，则物体关于 \(x\) 轴，\(x O y\) 平面及原点 \(O\) 的转动惯量 \(I_x,I_(x y)\) 及 \(I_o\) 分别是
\[I_x=integral.triple_Omega(y^2+z^2)rho(x,y,z)dif v,\]
\[I_(x y)=integral.triple_Omega z^2 rho(x,y,z)dif v,\]
\[I_o=integral.triple_Omega(x^2+y^2+z^2)rho(x,y,z)dif v.\]

（3）物体对质点的引力

设物体占有空间域 \(Omega\)，在点 \((x,y,z)\) 处的密度为 \(rho(x,y,z)\)，\(Omega\) 外有一质点 \(M_0(x_0,y_0,z_0)\)，其质量为 \(m_0\)，假定 \(rho(x,y,z)\) 在 \(Omega\) 上连续，则物体对质点的引力为 \(arrow(F)={F_x,F_y,F_z}\)，其中
\[F_x=integral.triple_Omega(k m_0 rho(x,y,z)(x-x_0))/([(x-x_0)^2+(y-y_0)^2+(z-z_0)^2]^(3/2))dif v,\]
\[F_y=integral.triple_Omega(k m_0 rho(x,y,z)(y-y_0))/([(x-x_0)^2+(y-y_0)^2+(z-z_0)^2]^(3/2))dif v,\]
\[F_z=integral.triple_Omega(k m_0 rho(x,y,z)(z-z_0))/([(x-x_0)^2+(y-y_0)^2+(z-z_0)^2]^(3/2))dif v.\]

** （三）对弧长的曲线积分

*** 1. 对弧长的曲线积分的概念与性质

（1）对弧长曲线积分的定义

设 \(L\) 为 \(x O y\) 面内的一条以 \(A,B\) 为端点的光滑（或分段光滑）曲线弧，函数 \(f(x,y)\) 在 \(L\) 上有界，在 \(L\) 上任意插入 \(n-1\) 个点 \(M_1,M_2,dots,M_(n-1)\) 把 \(L\) 分成 \(n\) 个小弧段 \(accent(M_(i-1)M_i,⌢)\)（\(i=1,2,dots,n,M_0=A,M_n=B\)），长度为 \(Delta s_i\)，又在 \(accent(M_(i-1)M_i,⌢)\) 上任取一点 \((xi_i,eta_i)\)，作乘积 \(f(xi_i,eta_i)Delta s_i\)，并作和 \(sum_(i=1)^n f(xi_i,eta_i)Delta s_i\)，如果当各小弧段长度的最大值 \(lambda->0\) 时，这和的极限总存在［与 \(Delta s_i\) 的分法及 \((xi_i,eta_i)\) 的取法均无关］，则称此极限为函数 \(f(x,y)\) 在曲线弧 \(L\) 上对弧长的曲线积分或第一类曲线积分，记作 \(integral_L f(x,y)dif s\)，即
\[integral_L f(x,y)dif s=lim_(lambda->0)sum_(i=1)^n f(xi_i,eta_i)Delta s_i,\]
其中 \(f(x,y)\) 称为被积函数，\(f(x,y)dif s\) 称为被积表达式，\(x\) 与 \(y\) 称为积分变量，\(L\) 称为积分弧段。

此定义可以类似地推广到积分弧段为空间曲线弧 \(Gamma\) 的情形，即函数 \(f(x,y,z)\) 在曲线弧 \(Gamma\) 上对弧长的曲线积分
\[integral_Gamma f(x,y,z)dif s=lim_(lambda->0)sum_(i=1)^n f(xi_i,eta_i,zeta_i)Delta s_i.\]

（2）对弧长的曲线积分的性质

对弧长的曲线积分有类似于重积分的性质，例如
\[integral_L[k_1 f_1(x,y)+k_2 f_2(x,y)]dif s=k_1 integral_L f_1(x,y)dif s+k_2 integral_L f_2(x,y)dif s quad (k_1,k_2"为常数");\]
\[integral_L f(x,y)dif s=integral_(L_1)f(x,y)dif s+integral_(L_2)f(x,y)dif s quad (L=L_1+L_2).\]
设 \(f(x,y)\) 在 \(L\) 上连续，则在 \(L\) 上至少存在一点 \((xi,eta)\) 使得
\[integral_L f(x,y)dif s=f(xi,eta) dot S,\]
其中 \(S\) 为曲线弧 \(L\) 的长度。

*** 2. 对弧长的曲线积分的计算法

设 \(f(x,y)\) 在曲线弧 \(L\) 上有定义且连续，\(L\) 的参数方程为
\[cases(x=phi(t),y=psi(t)),quad (alpha<=t<=beta),\]
其中 \(phi(t),psi(t)\) 在 \([alpha,beta]\) 上具有一阶连续导数，且 \(phi'^2(t)+psi'^2(t)!=0\)，则
\[integral_L f(x,y)dif s=integral_alpha^beta f[phi(t),psi(t)]sqrt(phi'^2(t)+psi'^2(t))dif t.\]
若曲线 \(L\) 由方程
\[y=psi(x)quad (x_0<=x<=X)\]
给出，则
\[integral_L f(x,y)dif s=integral_(x_0)^X f[x,psi(x)]sqrt(1+psi'^2(x))dif x.\]
若曲线 \(L\) 由方程
\[r=r(theta)quad (alpha<=theta<=beta)\]
给出，则
\[integral_L f(x,y)dif s=integral_alpha^beta f[r(theta)cos theta,r(theta)sin theta]sqrt(r^2(theta)+r'^2(theta))dif theta.\]
若空间曲线弧 \(Gamma\) 由参数方程
\[x=x(t),quad y=y(t),quad z=z(t)quad (alpha<=t<=beta)\]
给出，则
\[integral_Gamma f(x,y,z)dif s=integral_alpha^beta f[x(t),y(t),z(t)]sqrt(x'^2(t)+y'^2(t)+z'^2(t))dif t.\]

*** 3. 对弧长曲线积分的应用

（1）质心坐标　设曲线形物体占有 \(x O y\) 平面上弧段 \(L\)，在点 \(P(x,y)\) 处的线密度为 \(rho(x,y)\)，假定 \(rho(x,y)\) 在 \(L\) 上连续，则曲线形物体质心坐标为
\[overline(x)=1/M integral_L x rho(x,y)dif s,quad overline(y)=1/M integral_L y rho(x,y)dif s,\]
其中 \(M=integral_L rho(x,y)dif s\)。若 \(rho(x,y)="常数"\)，则形心坐标为
\[overline(x)=1/S integral_L x dif s,quad overline(y)=1/S integral_L y dif s,\]
其中 \(S\) 是弧长。

（2）转动惯量　设曲线形物体占有 \(x O y\) 平面上弧段 \(L\)，在点 \(P(x,y)\) 处的线密度为 \(rho(x,y)\)，假定 \(rho(x,y)\) 在 \(L\) 上连续，则曲线形物体关于 \(x\) 轴和原点的转动惯量分别为
\[I_x=integral_L y^2 rho(x,y)dif s,quad I_o=integral_L(x^2+y^2)rho(x,y)dif s.\]

** （四）对坐标的曲线积分

*** 1. 对坐标的曲线积分的概念与性质

（1）对坐标曲线积分的定义

设 \(L\) 为 \(x O y\) 面内从点 \(A\) 到点 \(B\) 的一条有向光滑（或分段光滑）曲线弧，函数 \(P(x,y),Q(x,y)\) 在 \(L\) 上有界，在 \(L\) 上沿 \(L\) 的方向任意插入点列 \(M_1(x_1,y_1),M_2(x_2,y_2),dots,M_(n-1)(x_(n-1),y_(n-1))\) 把 \(L\) 分成 \(n\) 个有向小弧段 \(accent(M_(i-1)M_i,⌢)\)（\(i=1,2,dots,n;M_0=A,M_n=B\)）及 \(Delta x_i=x_i-x_(i-1),Delta y_i=y_i-y_(i-1)\)，点 \((xi_i,eta_i)\) 为 \(accent(M_(i-1)M_i,⌢)\) 上任意取定的点。如果当各小弧段长度的最大值 \(lambda->0\) 时，\(sum_(i=1)^n P(xi_i,eta_i)Delta x_i\) 极限总存在［与曲线的分法及 \((xi_i,eta_i)\) 的取法均无关］，则称此极限值为函数 \(P(x,y)\) 在有向曲线弧 \(L\) 上对坐标 \(x\) 的曲线积分，记作 \(integral_L P(x,y)dif x\)。类似地，如果极限 \(lim_(lambda->0)sum_(i=1)^n Q(xi_i,eta_i)Delta y_i\) 总存在［与曲线弧的分法及 \((xi_i,eta_i)\) 的取法均无关］，则称此极限为函数 \(Q(x,y)\) 在有向曲线弧 \(L\) 上对坐标 \(y\) 的曲线积分，记作 \(integral_L Q(x,y)dif y\)，即
\[integral_L P(x,y)dif x=lim_(lambda->0)sum_(i=1)^n P(xi_i,eta_i)Delta x_i,\]
\[integral_L Q(x,y)dif y=lim_(lambda->0)sum_(i=1)^n Q(xi_i,eta_i)Delta y_i,\]
其中 \(P(x,y),Q(x,y)\) 称为被积函数，\(L\) 称为积分弧段。

一般地
\[integral_L P(x,y)dif x+Q(x,y)dif y=integral_L P(x,y)dif x+integral_L Q(x,y)dif y.\]
上述定义可以类似地推广到积分弧段为空间有向曲线弧 \(Gamma\) 的情形：
\[integral_Gamma P(x,y,z)dif x+Q(x,y,z)dif y+R(x,y,z)dif z \
 =lim_(lambda->0)sum_(i=1)^n[P(xi_i,eta_i,zeta_i)Delta x_i+Q(xi_i,eta_i,zeta_i)Delta y_i+R(xi_i,eta_i,zeta_i)Delta z_i].\]

（2）对坐标曲线积分的性质

若 \(L=L_1+L_2\)，则
\[integral_L P(x,y)dif x+Q(x,y)dif y \
 =integral_(L_1)P(x,y)dif x+Q(x,y)dif y+integral_(L_2)P(x,y)dif x+Q(x,y)dif y.\]
设 \(L\) 是有向曲线弧，\(-L\) 是与 \(L\) 方向相反的有向曲线弧，则
\[integral_(-L)P dif x+Q dif y=-integral_L P dif x+Q dif y.\]

*** 2. 对坐标曲线积分的计算法

设 \(P(x,y),Q(x,y)\) 在有向曲线弧 \(L\) 上连续

（1）若 \(L\) 的参数方程为
\[cases(x=phi(t),y=psi(t)),\]
当 \(t\) 单调地由 \(alpha\) 变到 \(beta\) 时，点 \(M(x,y)\) 从 \(L\) 的起点 \(A\) 沿 \(L\) 运动到 \(B\)，\(phi(t),psi(t)\) 在以 \(alpha,beta\) 为端点的闭区间上具有一阶连续导数，且 \(phi'^2(t)+psi'^2(t)!=0\)，则
\[integral_L P(x,y)dif x+Q(x,y)dif y=integral_alpha^beta{P[phi(t),psi(t)]phi'(t)+Q[phi(t),psi(t)]psi'(t)}dif t.\]

（2）若 \(L\) 的方程为 \(y=psi(x)\)，当 \(x\) 单调地由 \(a\) 变到 \(b\) 时，点 \(M(x,y)\) 从 \(L\) 起点 \(A\) 沿 \(L\) 运动到 \(B\)，\(psi(x)\) 在以 \(a,b\) 为端点的闭区间上具有一阶连续导数，则
\[integral_L P(x,y)dif x+Q(x,y)dif y=integral_a^b{P[x,psi(x)]+Q[x,psi(x)]psi'(x)}dif x.\]
若空间曲线弧 \(Gamma\) 由参数方程 \(x=x(t),y=y(t),z=z(t)\) 给出，则
\[integral_Gamma P(x,y,z)dif x+Q(x,y,z)dif y+R(x,y,z)dif z \
 =integral_alpha^beta{P[x(t),y(t),z(t)]x'(t)+Q[x(t),y(t),z(t)]y'(t)+R[x(t),y(t),z(t)]z'(t)}dif t,\]
其中 \(alpha\) 对应于 \(Gamma\) 的起点，\(beta\) 对应于 \(Gamma\) 的终点。

*** 3. 两类曲线积分之间的关系

\[integral_L P dif x+Q dif y=integral_L(P cos alpha+Q cos beta)dif s.\]
其中 \(alpha=alpha(x,y),beta=beta(x,y)\) 为有向曲线弧 \(L\) 上点 \((x,y)\) 处的正向切线向量的方向角。

*** 4. 格林公式及其应用

（1）格林公式　设闭区域 \(D\) 由分段光滑曲线 \(L\) 围成，函数 \(P(x,y)\) 及 \(Q(x,y)\) 在 \(D\) 上具有一阶连续偏导数，则有
\[integral.double_D((partial Q)/(partial x)-(partial P)/(partial y))dif x dif y=integral.cont_L P dif x+Q dif y,\]
其中 \(L\) 是 \(D\) 取正向的边界曲线。

若取 \(P=-y,Q=x\)，则 \(L\) 所围成的区域 \(D\) 的面积
\[A=1/2 integral.cont_L -y dif x+x dif y.\]

（2）平面上曲线积分与路径无关的条件

设 \(P(x,y),Q(x,y)\) 在单连通域 \(G\) 内具有一阶连续偏导数，则曲线积分 \(integral_L P dif x+Q dif y\) 在 \(G\) 内与路径无关（或沿 \(G\) 内任意闭曲线的曲线积分为零）的充分必要条件是在 \(G\) 内处处有
\[(partial P)/(partial y)=(partial Q)/(partial x).\]

（3）二元函数的全微分求积

设 \(P(x,y),Q(x,y)\) 在单连通域 \(G\) 内具有一阶连续偏导数，则 \(P(x,y)dif x+Q(x,y)dif y\) 在 \(G\) 内为某一函数 \(u(x,y)\) 的全微分的充分必要条件是等式
\[(partial P)/(partial y)=(partial Q)/(partial x)\]
在 \(G\) 内恒成立。
\[u(x,y)=integral_((x_0,y_0))^((x,y))P(x,y)dif x+Q(x,y)dif y+C \
 =integral_(x_0)^x P(x,y_0)dif x+integral_(y_0)^y Q(x,y)dif y+C.\]
或
\[u(x,y)=integral_(y_0)^y Q(x_0,y)dif y+integral_(x_0)^x P(x,y)dif x+C.\]

*** 5. 对坐标曲线积分的应用

设质点在力
\[bold(F)(x,y)=F_x(x,y)bold(i)+F_y(x,y)bold(j)\]
作用下，沿平面曲线 \(C\) 由 \(A\) 点移动到 \(B\) 点，其中 \(F_x(x,y),F_y(x,y)\) 在 \(C\) 上连续，则质点在移动过程中 \(bold(F)\) 所做的功
\[W=integral_C F_x(x,y)dif x+F_y(x,y)dif y.\]

** （五）对面积的曲面积分

*** 1. 对面积的曲面积分的概念与性质

（1）对面积曲面积分的定义

设曲面 \(Sigma\) 是光滑（或分片光滑）的，函数 \(f(x,y,z)\) 在 \(Sigma\) 上有界，把 \(Sigma\) 任意分成 \(n\) 小块 \(Delta S_i\)（\(Delta S_i\) 同时也代表第 \(i\) 小块曲面的面积），设 \((xi_i,eta_i,zeta_i)\) 是 \(Delta S_i\) 上任意取定的一点，作乘积 \(f(xi_i,eta_i,zeta_i)Delta S_i\)（\(i=1,2,dots,n\)），并作和 \(sum_(i=1)^n f(xi_i,eta_i,zeta_i)Delta S_i\)。如果当各小块曲面的直径的最大值 \(lambda->0\) 时，该和的极限总存在［与 \(Delta S_i\) 的分法及 \((xi_i,eta_i,zeta_i)\) 的取法均无关］，则称此极限值为函数 \(f(x,y,z)\) 在曲面 \(Sigma\) 上对面积的曲面积分或第一类曲面积分，记作 \(integral.double_Sigma f(x,y,z)dif S\)，即
\[integral.double_Sigma f(x,y,z)dif S=lim_(lambda->0)sum_(i=1)^n f(xi_i,eta_i,zeta_i)Delta S_i,\]
其中 \(f(x,y,z)\) 称为被积函数，\(Sigma\) 称为积分曲面。

（2）对面积的曲面积分的性质　类似于对弧长的曲线积分的性质。

*** 2. 对面积的曲面积分的计算法

设积分曲面 \(Sigma\) 由方程 \(z=z(x,y)\) 给出，\(Sigma\) 在 \(x O y\) 平面上的投影区域为 \(D_(x y)\)，函数 \(z=z(x,y)\) 在 \(D_(x y)\) 上具有连续偏导数，被积函数 \(f(x,y,z)\) 在 \(Sigma\) 上连续，则
\[integral.double_Sigma f(x,y,z)dif S=integral.double_(D_(x y))f(x,y,z(x,y))sqrt(1+z'_x^2(x,y)+z'_y^2(x,y))dif x dif y.\]

*** 3. 对面积的曲面积分的应用

设有一分布着质量的曲面 \(Sigma\)，在点 \((x,y,z)\) 处的面密度为 \(rho(x,y,z)\)，假定 \(rho(x,y,z)\) 在 \(Sigma\) 上连续，则质心坐标为
\[overline(x)=1/M integral.double_Sigma x rho(x,y,z)dif S,\]
\[overline(y)=1/M integral.double_Sigma y rho(x,y,z)dif S,\]
\[overline(z)=1/M integral.double_Sigma z rho(x,y,z)dif S,\]
其中 \(M=integral.double_Sigma rho(x,y,z)dif S\)。特别地 \(rho(x,y,z)="常数"\)，则形心坐标
\[overline(x)=1/S integral.double_Sigma x dif S,quad overline(y)=1/S integral.double_Sigma y dif S,quad overline(z)=1/S integral.double_Sigma z dif S,\]
其中 \(S\) 为曲面 \(Sigma\) 的面积。

上述曲面关于 \(x\) 轴，\(x O y\) 平面，原点的转动惯量分别为
\[I_x=integral.double_Sigma(y^2+z^2)rho(x,y,z)dif S,\]
\[I_(x y)=integral.double_Sigma z^2 rho(x,y,z)dif S,\]
\[I_o=integral.double_Sigma(x^2+y^2+z^2)rho(x,y,z)dif S.\]

** （六）对坐标的曲面积分

*** 1. 对坐标的曲面积分的概念与性质

（1）对坐标曲面积分的定义

设 \(Sigma\) 为光滑（或分片光滑）的有向曲面，函数 \(R(x,y,z)\) 在 \(Sigma\) 上有界，把 \(Sigma\) 任意分成 \(n\) 块小曲面 \(Delta S_i\)（\(Delta S_i\) 又表示第 \(i\) 小块曲面的面积），\(Delta S_i\) 在 \(x O y\) 平面上的投影为 \((Delta S_i)_(x y)\)，\((xi_i,eta_i,zeta_i)\) 是 \(Delta S_i\) 上任意取定的一点，如果当各小块曲面的直径的最大值 \(lambda->0\) 时，
\[lim_(lambda->0)sum_(i=1)^n R(xi_i,eta_i,zeta_i)(Delta S_i)_(x y)\]
总存在［与曲面的分法及 \((xi_i,eta_i,zeta_i)\) 的取法均无关］，则称此极限值为函数 \(R(x,y,z)\) 在有向曲面 \(Sigma\) 上对坐标 \(x,y\) 的曲面积分，记作 \(integral.double_Sigma R(x,y,z)dif x dif y\)，即
\[integral.double_Sigma R(x,y,z)dif x dif y=lim_(lambda->0)sum_(i=1)^n R(xi_i,eta_i,zeta_i)(Delta S_i)_(x y),\]
其中 \(R(x,y,z)\) 称为被积函数，\(Sigma\) 称为积分曲面。

类似地
\[integral.double_Sigma P(x,y,z)dif y dif z=lim_(lambda->0)sum_(i=1)^n P(xi_i,eta_i,zeta_i)(Delta S_i)_(y z),\]
\[integral.double_Sigma Q(x,y,z)dif z dif x=lim_(lambda->0)sum_(i=1)^n Q(xi_i,eta_i,zeta_i)(Delta S_i)_(z x).\]
一般地
\[integral.double_Sigma P(x,y,z)dif y dif z+Q(x,y,z)dif z dif x+R(x,y,z)dif x dif y \
 =integral.double_Sigma P(x,y,z)dif y dif z+integral.double_Sigma Q(x,y,z)dif z dif x+integral.double_Sigma R(x,y,z)dif x dif y.\]

（2）对坐标曲面积分的性质

类似于对坐标的曲线积分，例如

若把 \(Sigma\) 分成 \(Sigma_1\) 和 \(Sigma_2\)，则
\[integral.double_Sigma P dif y dif z+Q dif z dif x+R dif x dif y \
 =integral.double_(Sigma_1)P dif y dif z+Q dif z dif x+R dif x dif y+integral.double_(Sigma_2)P dif y dif z+Q dif z dif x+R dif x dif y.\]
设 \(Sigma\) 是有向曲面，\(-Sigma\) 是和 \(Sigma\) 取相反侧的有向曲面，则
\[integral.double_(-Sigma)P dif y dif z+Q dif z dif x+R dif x dif y=-integral.double_Sigma P dif y dif z+Q dif z dif x+R dif x dif y.\]

*** 2. 对坐标的曲面积分的计算法

设积分曲面 \(Sigma\) 是由方程 \(z=z(x,y)\) 给出，\(Sigma\) 在 \(x O y\) 平面上投影区域为 \(D_(x y)\)，\(z=z(x,y)\) 在 \(D_(x y)\) 上具有一阶连续偏导数，被积函数 \(R(x,y,z)\) 在 \(Sigma\) 上连续，则
\[integral.double_Sigma R(x,y,z)dif x dif y=plus.minus integral.double_(D_(x y))R(x,y,z(x,y))dif x dif y,\]
若曲面 \(Sigma\) 是由方程 \(z=z(x,y)\) 所给出的曲面正侧，取正号，反之取负号。

类似地，若曲面 \(Sigma\) 由 \(x=x(y,z)\) 给出，则
\[integral.double_Sigma P(x,y,z)dif y dif z=plus.minus integral.double_(D_(y z))P(x(y,z),y,z)dif y dif z,\]
若曲面 \(Sigma\) 是由 \(x=x(y,z)\) 给出的曲面前侧，取正号，反之取负号。若曲面 \(Sigma\) 是由 \(y=y(x,z)\) 给出，则
\[integral.double_Sigma Q(x,y,z)dif z dif x=plus.minus integral.double_(D_(z x))Q(x,y(x,z),z)dif z dif x,\]
若积分曲面 \(Sigma\) 是由 \(y=y(x,z)\) 所给出曲面右侧，取正号，反之取负号。

*** 3. 两类曲面之间的关系

\[integral.double_Sigma P dif y dif z+Q dif z dif x+R dif x dif y=integral.double_Sigma(P cos alpha+Q cos beta+R cos gamma)dif S,\]
其中 \(cos alpha,cos beta,cos gamma\) 是有向曲面 \(Sigma\) 上点 \((x,y,z)\) 处的法向量的方向余弦。

*** 4. 高斯公式及应用

（1）高斯公式　设空间闭区域 \(Omega\) 是由分片光滑闭曲面 \(Sigma\) 所围成，函数 \(P(x,y,z),Q(x,y,z),R(x,y,z)\) 在 \(Omega\) 上具有一阶连续偏导数，则有
\[integral.triple_Omega((partial P)/(partial x)+(partial Q)/(partial y)+(partial R)/(partial z))dif v=integral.surf_Sigma P dif y dif z+Q dif z dif x+R dif x dif y,\]
其中 \(Sigma\) 是 \(Omega\) 的整个边界曲面取外侧。

（2）取 \(P=x,Q=y,R=z\)，则空间区域 \(Omega\) 的体积为
\[V=1/3 integral.surf_Sigma x dif y dif z+y dif z dif x+z dif x dif y.\]

*** 5. 通量与散度

（1）通量　设某向量场由
\[bold(A)(x,y,z)=P(x,y,z)bold(i)+Q(x,y,z)bold(j)+R(x,y,z)bold(k)\]
给出，其中 \(P,Q,R\) 具有一阶连续偏导数，\(Sigma\) 是场内的一片有向曲面，\(bold(n)^degree\) 是 \(Sigma\) 上点 \((x,y,z)\) 处的单位法向量，则 \(integral.double_Sigma bold(A) dot bold(n)^degree dif S\) 称为向量场 \(bold(A)\) 通过曲面 \(Sigma\) 向着指定侧的通量。

由定义知 \(integral.double_Sigma bold(A) dot bold(n)^degree dif S=integral.double_Sigma P(x,y,z)dif y dif z+Q(x,y,z)dif z dif x+R(x,y,z)dif x dif y\)。

（2）散度　设某向量场由
\[bold(A)(x,y,z)=P(x,y,z)bold(i)+Q(x,y,z)bold(j)+R(x,y,z)bold(k)\]
给出，则向量场 \(bold(A)\) 在场中一点 \((x,y,z)\) 处散度
\[op("div")bold(A)=(partial P)/(partial x)+(partial Q)/(partial y)+(partial R)/(partial z).\]

（3）高斯公式向量形式
\[integral.triple_Omega op("div")bold(A)dif v=integral.surf_Sigma bold(A) dot bold(n)^degree dif S=integral.surf_Sigma bold(A) dot dif bold(S)=integral.surf_Sigma A_n dif S\]
其中 \(Sigma\) 是空间闭区域 \(Omega\) 的边界曲面，而
\[dif bold(S)=bold(n)^degree dot dif S=bold(i)cos alpha dif S+bold(j)cos beta dif S+bold(k)cos gamma dif S,\]
\[A_n=bold(A) dot bold(n)^degree=P cos alpha+Q cos beta+R cos gamma.\]

*** 6. 斯托克斯公式

设 \(Gamma\) 为分段光滑的空间有向闭曲线，\(Sigma\) 是以 \(Gamma\) 为边界的分片光滑的有界曲面，\(Gamma\) 的正向与 \(Sigma\) 的侧面符合右手规则，函数 \(P(x,y,z),Q(x,y,z),R(x,y,z)\) 在包含 \(Sigma\) 在内的空间域内具有一阶连续偏导数，则
\[integral.cont_Gamma P(x,y,z)dif x+Q(x,y,z)dif y+R(x,y,z)dif z \
 =integral.double_Sigma mat(delim: "|",dif y dif z,dif z dif x,dif x dif y;partial/(partial x),partial/(partial y),partial/(partial z);P,Q,R) \
 =integral.double_Sigma((partial R)/(partial y)-(partial Q)/(partial z))dif y dif z+((partial P)/(partial z)-(partial R)/(partial x))dif z dif x+((partial Q)/(partial x)-(partial P)/(partial y))dif x dif y.\]

*** 7. 环流量与旋度

（1）环流量　向量场
\[bold(A)(x,y,z)=P(x,y,z)bold(i)+Q(x,y,z)bold(j)+R(x,y,z)bold(k)\]
沿场内有向闭曲线 \(Gamma\) 的曲线积分
\[integral.cont_Gamma bold(A) dot dif bold(s)=integral.cont_Gamma P dif x+Q dif y+R dif z\]
称为向量场 \(bold(A)\) 沿有向闭曲线 \(Gamma\) 的环流量。

（2）向量场的旋度　设有向量场
\[bold(A)(x,y,z)=P(x,y,z)bold(i)+Q(x,y,z)bold(j)+R(x,y,z)bold(k)\]
则向量场 \(bold(A)(x,y,z)\) 在场内一点 \((x,y,z)\) 处旋度
\[op("rot")bold(A)=mat(delim: "|",bold(i),bold(j),bold(k);partial/(partial x),partial/(partial y),partial/(partial z);P,Q,R) \
 =((partial R)/(partial y)-(partial Q)/(partial z))bold(i)+((partial P)/(partial z)-(partial R)/(partial x))bold(j)+((partial Q)/(partial x)-(partial P)/(partial y))bold(k).\]

（3）斯托克斯公式向量形式
\[integral.cont_Gamma bold(A) dot bold(t)^degree dif s=integral.cont_Gamma bold(A) dot dif bold(s)=integral.double_Sigma op("rot")bold(A) dot bold(n)^degree dif S,\]
或
\[integral.cont_Gamma A_t dif s=integral.double_Sigma(op("rot")bold(A))_n dif S.\]
其中 \(bold(n)^degree\) 为有向曲面 \(Sigma\) 在点 \((x,y,z)\) 处的单位法向量，\(bold(t)^degree\) 为 \(Sigma\) 正向边界曲线 \(Gamma\) 上点 \((x,y,z)\) 处的单位切向量，\((op("rot")bold(A))_n=op("rot")bold(A) dot bold(n)^degree\) 为 \(op("rot")bold(A)\) 在 \(Sigma\) 的法向量上投影，\(A_t=bold(A) dot bold(t)^degree\) 为向量 \(bold(A)\) 在 \(Gamma\) 切向量上的投影。
