#+TITLE: 随机变量的数字特征

* 考试内容解析

** （一）随机变量的数学期望

*** 1. 定义

（1）离散型随机变量的数学期望　设离散型随机变量 $X$ 的概率分布为
$$
P\left\{ X = x_{k} \right\} = p_{k},\quad k = 1,2,\ldots,
$$
如果无穷级数 $\sum_{k = 1}^{\infty}x_{k}p_{k}$ 绝对收敛，则称此无穷级数的和为随机变量 $X$ 的数学期望或均值，记作 $E(X)$，即
$$
E(X) = \sum_{k = 1}^{\infty}x_{k}p_{k}.
$$

（2）连续型随机变量的数学期望　设连续型随机变量 $X$ 的概率密度为 $f(x)$，如果反常积分 $\int_{- \infty}^{+ \infty}xf(x)dx$ 绝对收敛，则称此反常积分的值为随机变量 $X$ 的数学期望或均值，记作 $E(X)$，即
$$
E(X) = \int_{- \infty}^{+ \infty}xf(x)dx.
$$

说明　如果上述的无穷级数或反常积分不绝对收敛，则称随机变量的数学期望不存在。

*** 2. 性质

（1）设 $C$ 是常数，则有 $E(C) = C$。

（2）设 $X$ 是随机变量，$C$ 是常数，则有
$$
E(CX) = CE(X).
$$

（3）设 $X$ 和 $Y$ 是两个随机变量，则有
$$
E(X \pm Y) = E(X) \pm E(Y).
$$

（4）设随机变量 $X$ 和 $Y$ 相互独立，则有
$$
E(XY) = E(X)E(Y).
$$
在上面的性质中，均假设数学期望是存在的。

*** 3. 随机变量函数的数学期望

（1）一维随机变量函数的数学期望

设 $y = g(x)$ 是连续函数，$Y$ 是随机变量 $X$ 的函数：$Y = g(X)$。

1° 设 $X$ 是离散型随机变量，其概率分布为
$$
P\left\{ X = x_{k} \right\} = p_{k},\quad k = 1,2,\ldots,
$$
如果无穷级数 $\sum_{k = 1}^{\infty}g\left( x_{k} \right)p_{k}$ 绝对收敛，则随机变量 $Y = g(X)$ 的数学期望为
$$
E(Y) = E\left\lbrack g(X) \right\rbrack = \sum_{k = 1}^{\infty}g\left( x_{k} \right)p_{k}.
$$

2° 设连续型随机变量 $X$ 的概率密度为 $f(x)$，如果反常积分 $\int_{- \infty}^{+ \infty}g(x)f(x)dx$ 绝对收敛，则随机变量 $Y = g(X)$ 的数学期望为
$$
E(Y) = E\left\lbrack g(X) \right\rbrack = \int_{- \infty}^{+ \infty}g(x)f(x)dx.
$$

（2）二维随机变量函数的数学期望

设 $z = g(x,y)$ 是连续函数，$Z$ 是随机变量 $X,Y$ 的函数：$Z = g(X,Y)$。

1° 设二维离散型随机变量 $(X,Y)$ 的概率分布为
$$
P\left\{ X = x_{i},Y = y_{j} \right\} = p_{ij},\quad i,j = 1,2,\ldots,
$$
如果无穷级数 $\sum_{j = 1}^{\infty}\sum_{i = 1}^{\infty}g\left( x_{i},y_{j} \right)p_{ij}$ 绝对收敛，则随机变量 $Z = g(X,Y)$ 的数学期望为
$$
E(Z) = E\left\lbrack g(X,Y) \right\rbrack = \sum_{j = 1}^{\infty}\sum_{i = 1}^{\infty}g\left( x_{i},y_{j} \right)p_{ij}.
$$

2° 设二维连续型随机变量 $(X,Y)$ 的概率密度为 $f(x,y)$，如果反常积分 $\int_{- \infty}^{+ \infty}\int_{- \infty}^{+ \infty}g(x,y)f(x,y)dxdy$ 绝对收敛，则随机变量 $Z = g(X,Y)$ 的数学期望为
$$
E(Z) = E\left\lbrack g(X,Y) \right\rbrack = \int_{- \infty}^{+ \infty}\int_{- \infty}^{+ \infty}g(x,y)f(x,y)dxdy.
$$

** （二）随机变量的方差

*** 1. 定义

设 $X$ 是一个随机变量，如果数学期望 $E\left\{ \left\lbrack X - E(X) \right\rbrack^{2} \right\}$ 存在，则称之为 $X$ 的方差，记作 $D(X)$，即
$$
D(X) = E\left\{ \left\lbrack X - E(X) \right\rbrack^{2} \right\}.
$$
称 $\sqrt{D(X)}$ 为随机变量 $X$ 的标准差或均方差，记作 $\sigma(X)$，即
$$
\sigma(X) = \sqrt{D(X)}.
$$

*** 2. 计算方差的公式

$$
D(X) = E\left( X^{2} \right) - \left\lbrack E(X) \right\rbrack^{2.}
$$

*** 3. 性质

（1）设 $C$ 是常数，则 $D(C) = 0$。

（2）设 $X$ 是随机变量，$C$ 是常数，则有
$$
D(X + C) = D(X).
$$

（3）设 $X$ 是随机变量，$C$ 是常数，则有
$$
D(CX) = C^{2}D(X).
$$

（4）设随机变量 $X$ 和 $Y$ 相互独立，则有
$$
D(X \pm Y) = D(X) + D(Y).
$$

（5）$D(X) = 0$ 的充分必要条件是 $X$ 以概率1取常数 $C$，即
$$
P\left\{ X = C \right\} = 1,
$$
这里 $C = E(X)$。在上面的性质中，均假设方差是存在的。

** （三）常用随机变量的数学期望和方差

1. 如果 $X \sim (0 - 1)$，即 $P\left\{ X = i \right\} = p^{i}(1 - p)^{1 - i}(i = 0,1)$，则
$$
E(X) = p,\quad D(X) = p(1 - p).
$$

2. 如果 $X \sim B(n,p)$，则
$$
E(X) = np,\quad D(X) = np(1 - p).
$$

3. 如果 $X \sim P(\lambda)$，则
$$
E(X) = \lambda,\quad D(X) = \lambda.
$$

4. 如果 $X$ 在区间 $(a,b)$ 上服从均匀分布，即 $X \sim U(a,b)$，则
$$
E(X) = \frac{a + b}{2},\quad D(X) = \frac{(b - a)^{2}}{12.}
$$

5. 如果 $X$ 服从参数为 $\lambda$（$\lambda > 0$ 是常数）的指数分布，即 $X \sim E(\lambda)$，则
$$
E(X) = \frac{1}{\lambda},\quad D(X) = \frac{1}{\lambda^{2.}}
$$

6. 如果 $X$ 服从参数为 $\mu,\sigma(\sigma > 0)$ 的正态分布，即 $X \sim N\left( \mu,\sigma^{2} \right)$，则
$$
E(X) = \mu,\quad D(X) = \sigma^{2.}
$$

** （四）随机变量 $X$ 的标准化随机变量

如果随机变量 $X$ 的方差 $D(X)$ 存在，且 $D(X) > 0$，则称
$$
X^{\ast} = \frac{X - E(X)}{\sqrt{D(X)}}
$$
为 $X$ 的标准化随机变量。易知
$$
E\left( X^{\ast} \right) = 0,\quad D\left( X^{\ast} \right) = 1.
$$

** （五）随机变量的矩

设 $X$ 是随机变量，如果
$$
E\left( X^{k} \right),\quad k = 1,2,\ldots
$$
存在，则称之为 $X$ 的 $k$ 阶原点矩，简称 $k$ 阶矩。记作 $\mu_{k}$，即 $\mu_{k} = E\left( X^{k} \right),k = 1,2,\ldots$，如果
$$
E\left\{ \left\lbrack X - E(X) \right\rbrack^{k} \right\},\quad k = 1,2,\ldots
$$
存在，则称之为 $X$ 的 $k$ 阶中心矩。

设 $X$ 和 $Y$ 是两个随机变量，如果
$$
E\left( X^{k}Y^{l} \right),\quad k,l = 1,2,\ldots
$$
存在，则称之为 $X$ 和 $Y$ 的 $k + l$ 阶混合矩。如果
$$
E\left\{ \left\lbrack X - E(X) \right\rbrack^{k}\left\lbrack Y - E(Y) \right\rbrack^{l} \right\},\quad k,l = 1,2,\ldots
$$
存在，则称之为 $X$ 和 $Y$ 的 $k + l$ 阶混合中心矩。

** （六）协方差和相关系数

*** 1. 协方差

（1）定义　对于随机变量 $X$ 和 $Y$，如果 $E\left\{ \left\lbrack X - E(X) \right\rbrack\left\lbrack Y - E(Y) \right\rbrack \right\}$ 存在，则称之为 $X$ 和 $Y$ 的协方差，记作 $\text{ Cov}(X,Y)$，即
$$
\text{ Cov}(X,Y) = E\left\{ \left\lbrack X - E(X) \right\rbrack\left\lbrack Y - E(Y) \right\rbrack \right\}.
$$

（2）公式　对于任意两个随机变量 $X$ 和 $Y$，有
$$
\text{ Cov}(X,Y) = E(XY) - E(X)E(Y),
$$
$$
D(X \pm Y) = D(X) + D(Y) \pm 2\text{ Cov}(X,Y).
$$

（3）性质

① $\text{ Cov}(X,Y) = \text{Cov}(Y,X)$。

② $\text{ Cov}(aX,bY) = ab\text{ Cov}(X,Y)$，其中 $a,b$ 是常数。

③ $\text{ Cov}\left( X_{1} + X_{2},Y \right) = \text{Cov}\left( X_{1},Y \right) + \text{Cov}\left( X_{2},Y \right)$。

*** 2. 相关系数

（1）定义　对于随机变量 $X$ 和 $Y$，如果 $D(X) \neq 0,D(Y) \neq 0$，则称 $\frac{\text{ Cov}(X,Y)}{\sqrt{D(X)}\sqrt{D(Y)}}$ 为 $X$ 和 $Y$ 的相关系数，记为 $\rho_{XY}$，即
$$
\rho_{XY} = \frac{\text{Cov}(X,Y)}{\sqrt{D(X)}\sqrt{D(Y)}}.
$$
由定义可知 $\rho_{XY} = \text{Cov}\left( X^{\ast},Y^{\ast} \right)$，其中 $X^{\ast}$ 和 $Y^{\ast}$ 分别是 $X$ 和 $Y$ 的标准化随机变量。

（2）随机变量 $X$ 和 $Y$ 不相关　如果随机变量 $X$ 和 $Y$ 的相关系数 $\rho_{XY} = 0$，则称 $X$ 和 $Y$ 不相关。如果随机变量 $X$ 和 $Y$ 相互独立，则 $X$ 和 $Y$ 不相关；但 $X$ 和 $Y$ 不相关时，$X$ 和 $Y$ 却不一定相互独立。

设 $(X,Y) \sim N\left( \mu_{1},\mu_{2};\sigma_{1}^{2},\sigma_{2}^{2};\rho \right)$，则 $E(X) = \mu_{1},E(Y) = \mu_{2},D(X) = \sigma_{1}^{2},D(Y) = \sigma_{2}^{2},\rho_{XY} = \rho$；随机变量 $X$ 和 $Y$ 相互独立的充分必要条件是 $\rho = 0$。即如果二维随机变量 $(X,Y)$ 服从二维正态分布，则 $X$ 和 $Y$ 相互独立的充分必要条件是 $X$ 和 $Y$ 不相关。

（3）相关系数的性质

① $\left| \rho_{XY} \right| \leq 1$。

② $\left| \rho_{XY} \right| = 1$ 的充分必要条件是存在常数 $a$ 和 $b$，使得
$$
P\left\{ Y = a + bX \right\} = 1.
$$
