#+TITLE: 参数估计
#+TYPST_MATH: t

* 考试内容解析

** （一）点估计

*** 1. 点估计的概念

设总体 \(X\) 的分布形式已知，但含有未知参数 \(theta\)；或者总体的某数字特征（例如数学期望或方差）存在但未知，从总体 \(X\) 中抽取样本 \(X_1,X_2,dots,X_n\)，相应的样本值为 \(x_1,x_2,dots,x_n\)。借助于样本来估计未知参数的值的问题就是参数的点估计问题。要解决点估计问题，就是要构造一个统计量 \(hat(theta)(X_1,X_2,dots,X_n)\)，用它的观测值 \(hat(theta)(x_1,x_2,dots,x_n)\) 作为未知参数 \(theta\) 的近似值，称 \(hat(theta)(X_1,X_2,dots,X_n)\) 为未知参数 \(theta\) 的估计量，\(hat(theta)(x_1,x_2,dots,x_n)\) 为 \(theta\) 的估计值。在不至于混淆的情况下将 \(theta\) 的估计量和估计值统称为 \(theta\) 的估计。

求点估计有两种常用的方法——矩估计法和最大似然估计法。

*** 2. 矩估计法

设总体 \(X\) 为连续型随机变量，概率密度为 \(f(x;theta_1,theta_2,dots,theta_k)\)，或设总体 \(X\) 为离散型随机变量，概率分布为
\[P{X=x_i}=p(x_i;theta_1,theta_2,dots,theta_k), quad i=1,2,dots,\]
其中 \(theta_1,theta_2,dots,theta_k\) 是待估参数。假设总体 \(X\) 的 \(l\) 阶原点矩
\[mu_l=E(X^l)=integral_(-infinity)^(+infinity) x^l f(x;theta_1,theta_2,dots,theta_k) dif x\]
或
\[mu_l=E(X^l)=sum_(i=1)^infinity x_i^l p(x_i;theta_1,theta_2,dots,theta_k), quad l=1,2,dots,k\]
均存在，一般来说，它们是 \(theta_1,theta_2,dots,theta_k\) 的函数，记作
\[mu_l=mu_l(theta_1,theta_2,dots,theta_k).\]
设 \(X_1,X_2,dots,X_n\) 是来自总体 \(X\) 的样本，根据辛钦大数定律可知样本 \(l\) 阶原点矩
\[A_l=1/n sum_(i=1)^n X_i^l\]
依概率收敛于总体 \(l\) 阶原点矩 \(mu_l (l=1,2,dots,k)\)。根据依概率收敛的性质可知样本矩的连续函数依概率收敛于相应的总体矩的同一连续函数。因此，我们用样本矩作为相应的总体矩的估计量，用样本矩的连续函数作为相应的总体矩的连续函数的估计量，由此求得未知参数 \(theta_1,theta_2,dots,theta_k\) 的估计量。这种求估计量的方法称为矩估计法。

矩估计法的具体做法是：求出总体 \(X\) 的 \(1,2,dots,k\) 阶原点矩
\[mu_l=mu_l(theta_1,theta_2,dots,theta_k), quad l=1,2,dots,k;\]
解此方程组，求得未知参数 \(theta_1,theta_2,dots,theta_k\) 关于 \(mu_1,mu_2,dots,mu_k\) 的函数表达式
\[theta_j=theta_j(mu_1,mu_2,dots,mu_k), quad j=1,2,dots,k;\]
用样本矩 \(A_l\) 代替总体矩 \(mu_l (l=1,2,dots,k)\)，得到未知参数 \(theta_j (j=1,2,dots,k)\) 的矩估计量
\[hat(theta)_j=theta_j(A_1,A_2,dots,A_k), quad j=1,2,dots,k,\]
矩估计量的观测值
\[hat(theta)_j=theta_j(a_1,a_2,dots,a_k), quad j=1,2,dots,k\]
就是未知参数 \(theta_j (j=1,2,dots,k)\) 的矩估计值。

*** 3. 最大似然估计法

（1）设总体 \(X\) 是离散型随机变量，概率分布为
\[P{X=t_i}=p(t_i;theta), quad i=1,2,dots,\]
其中 \(theta\) 是待估参数，\(theta\) 的取值范围是 \(Theta\)。设 \(X_1,X_2,dots,X_n\) 是来自总体 \(X\) 的样本，\(x_1,x_2,dots,x_n\) 是样本值，称函数
\[L(theta)=L(x_1,x_2,dots,x_n;theta)=product_(i=1)^n p(x_i;theta), quad theta in Theta\]
为样本 \(x_1,x_2,dots,x_n\) 的似然函数。如果 \(hat(theta)in Theta\) 使得
\[L(hat(theta))=max_(theta in Theta) L(theta),\]
这样的 \(hat(theta)\) 与 \(x_1,x_2,dots,x_n\) 有关，记作 \(hat(theta)(x_1,x_2,dots,x_n)\)，称为未知参数 \(theta\) 的最大似然估计值。相应的统计量 \(hat(theta)(X_1,X_2,dots,X_n)\) 称为 \(theta\) 的最大似然估计量。一般统称为 \(theta\) 的最大似然估计。

（2）设总体 \(X\) 是连续型随机变量，概率密度为 \(f(x;theta)\)，\(theta\) 是待估参数，则似然函数为
\[L(theta)=L(x_1,x_2,dots,x_n;theta)=product_(i=1)^n f(x_i;theta), quad theta in Theta.\]

（3）如果 \(L(theta)\) 或 \(ln L(theta)\) 关于 \(theta\) 可微，则 \(theta\) 往往可以从方程
\[(dif L(theta))/(dif theta)=0 quad "或" quad (dif ln L(theta))/(dif theta)=0\]
中解得。

（4）如果总体 \(X\) 的分布中含有 \(k\) 个未知参数 \(theta_1,theta_2,dots,theta_k\)，则似然函数是这些参数的函数：\(L=L(theta_1,theta_2,dots,theta_k)\)。分别令
\[(partial L)/(partial theta_j)=0 quad "或" quad (partial ln L)/(partial theta_j)=0, quad j=1,2,dots,k,\]
解上面的方程组，可得各个待估参数 \(theta_j\) 的最大似然估计值 \(hat(theta)_j(x_1,x_2,dots,x_n)\)，从而得到最大似然估计量 \(hat(theta)_j(X_1,X_2,dots,X_n) (j=1,2,dots,k)\)。

（5）最大似然估计具有如下性质：设 \(theta\) 的函数 \(phi=phi(theta) (theta in Theta)\) 具有单值反函数 \(theta=theta(phi) (phi in Phi)\)，\(hat(theta)\) 是总体 \(X\) 的分布中未知参数 \(theta\) 的最大似然估计，则 \(hat(phi)=phi(hat(theta))\) 是 \(phi=phi(theta)\) 的最大似然估计。例如，设总体方差 \(sigma^2\) 的最大似然估计为 \(hat(sigma)^2=1/n sum_(i=1)^n(X_i-overline(X))^2\)，则总体标准差的最大似然估计为 \(hat(sigma)=sqrt(1/n sum_(i=1)^n(X_i-overline(X))^2)\)。

*** 4. 估计量的评选标准

（1）无偏性　如果 \(theta\) 的估计量 \(hat(theta)=hat(theta)(X_1,X_2,dots,X_n)\) 的数学期望 \(E(hat(theta))\) 存在，且对于任意 \(theta in Theta\)，有
\[E(hat(theta))=theta,\]
则称 \(hat(theta)=hat(theta)(X_1,X_2,dots,X_n)\) 是未知参数 \(theta\) 的无偏估计量。

（2）有效性　设 \(hat(theta)_1=hat(theta)_1(X_1,X_2,dots,X_n)\) 和 \(hat(theta)_2=hat(theta)_2(X_1,X_2,dots,X_n)\) 都是未知参数 \(theta\) 的无偏估计量，如果对于任意 \(theta in Theta\)，有
\[D(hat(theta)_1)<=D(hat(theta)_2),\]
且至少有一个 \(theta in Theta\)，使上式中的不等号成立，则称 \(hat(theta)_1=hat(theta)_1(X_1,X_2,dots,X_n)\) 比 \(hat(theta)_2=hat(theta)_2(X_1,X_2,dots,X_n)\) 更有效。

（3）一致性（相合性）　设 \(hat(theta)(X_1,X_2,dots,X_n)\) 为未知参数 \(theta\) 的估计量，如果对于任意 \(theta in Theta\)，当 \(n->infinity\) 时，\(hat(theta)(X_1,X_2,dots,X_n)\) 依概率收敛于 \(theta\)，则称 \(hat(theta)(X_1,X_2,dots,X_n)\) 为未知参数 \(theta\) 的一致估计量或相合估计量。

** （二）区间估计

*** 1. 置信区间

设总体 \(X\) 的分布函数为 \(F(x;theta)\)，其中 \(theta\) 是未知参数。从总体 \(X\) 中抽取样本 \(X_1,X_2,dots,X_n\)，对于给定的 \(alpha (0<alpha<1)\)，如果两个统计量 \(theta_1=theta_1(X_1,X_2,dots,X_n)\) 和 \(theta_2=theta_2(X_1,X_2,dots,X_n)\)，对于任意 \(theta in Theta\) 满足
\[P{theta_1(X_1,X_2,dots,X_n)<theta<theta_2(X_1,X_2,dots,X_n)}=1-alpha,\]
则称随机区间 \((theta_1,theta_2)\) 为未知参数 \(theta\) 的置信水平是 \(1-alpha\) 的置信区间，\(theta_1(X_1,X_2,dots,X_n)\) 和 \(theta_2(X_1,X_2,dots,X_n)\) 分别称为这一双侧置信区间的置信下限和置信上限，\(1-alpha\) 称为置信水平（或置信度）。

*** 2. 单个正态总体均值和方差的置信区间

设 \(X tilde N(mu,sigma^2)\)，从总体 \(X\) 中抽取样本 \(X_1,X_2,dots,X_n\)，样本均值为 \(overline(X)\)，样本方差为 \(S^2\)。

（1）\(sigma^2\) 已知，\(mu\) 的置信水平是 \(1-alpha\) 的置信区间为
\[(overline(x)-sigma/sqrt(n)u_(alpha/2),overline(x)+sigma/sqrt(n)u_(alpha/2)).\]

（2）\(sigma^2\) 未知，\(mu\) 的置信水平是 \(1-alpha\) 的置信区间为
\[(overline(x)-s/sqrt(n)t_(alpha/2)(n-1),overline(x)+s/sqrt(n)t_(alpha/2)(n-1)).\]

（3）\(mu\) 已知，\(sigma^2\) 的置信水平是 \(1-alpha\) 的置信区间为
\[((sum_(i=1)^n(x_i-mu)^2)/(chi_(alpha/2)^2(n)),(sum_(i=1)^n(x_i-mu)^2)/(chi_(1-alpha/2)^2(n))).\]

（4）\(mu\) 未知，\(sigma^2\) 的置信水平是 \(1-alpha\) 的置信区间为
\[(((n-1)s^2)/(chi_(alpha/2)^2(n-1)),((n-1)s^2)/(chi_(1-alpha/2)^2(n-1))),\]
标准差 \(sigma\) 的置信水平是 \(1-alpha\) 的置信区间为
\[((sqrt(n-1)s)/sqrt(chi_(alpha/2)^2(n-1)),(sqrt(n-1)s)/sqrt(chi_(1-alpha/2)^2(n-1))).\]

*** 3. 两个正态总体均值差和方差比的置信区间

设 \(X tilde N(mu_1,sigma_1^2),Y tilde N(mu_2,sigma_2^2)\)，从总体 \(X\) 中抽取样本 \(X_1,X_2,dots,X_(n_1)\)，样本均值为 \(overline(X)\)，样本方差为 \(S_1^2\)；从总体 \(Y\) 中抽取样本 \(Y_1,Y_2,dots,Y_(n_2)\)，样本均值为 \(overline(Y)\)，样本方差为 \(S_2^2\)，并且两个样本是相互独立的。

（1）\(sigma_1^2\) 和 \(sigma_2^2\) 已知，\(mu_1-mu_2\) 的置信水平是 \(1-alpha\) 的置信区间为
\[(overline(x)-overline(y)-u_(alpha/2)sqrt(sigma_1^2/n_1+sigma_2^2/n_2),overline(x)-overline(y)+u_(alpha/2)sqrt(sigma_1^2/n_1+sigma_2^2/n_2)).\]

（2）\(sigma_1^2=sigma_2^2=sigma^2\) 未知，\(mu_1-mu_2\) 的置信水平是 \(1-alpha\) 的置信区间为
\[(overline(x)-overline(y)-t_(alpha/2)(n_1+n_2-2)s_w sqrt(1/n_1+1/n_2),overline(x)-overline(y)+t_(alpha/2)(n_1+n_2-2)s_w sqrt(1/n_1+1/n_2)),\]
其中
\[s_w^2=((n_1-1)s_1^2+(n_2-1)s_2^2)/(n_1+n_2-2), quad s_w=sqrt(s_w^2).\]

（3）\(mu_1\) 和 \(mu_2\) 已知，\(sigma_1^2/sigma_2^2\) 的置信水平是 \(1-alpha\) 的置信区间为
\[((n_2 sum_(i=1)^(n_1)(x_i-mu_1)^2)/(n_1 sum_(j=1)^(n_2)(y_j-mu_2)^2) dot 1/F_(alpha/2)(n_1,n_2),(n_2 sum_(i=1)^(n_1)(x_i-mu_1)^2)/(n_1 sum_(j=1)^(n_2)(y_j-mu_2)^2) dot F_(alpha/2)(n_2,n_1)).\]

（4）\(mu_1\) 和 \(mu_2\) 未知，\(sigma_1^2/sigma_2^2\) 的置信水平是 \(1-alpha\) 的置信区间为
\[(s_1^2/s_2^2 dot 1/F_(alpha/2)(n_1-1,n_2-1),s_1^2/s_2^2 dot F_(alpha/2)(n_2-1,n_1-1)).\]
